import React,{useEffect,useMemo,useState} from "react";
import {loadMonthlyScorecardDatasetWithRetry} from "./monthlyScorecardService";
import {buildLaborOptimization} from "./laborOptimization";
import MonthlySchoolScorecard from "./MonthlySchoolScorecard";
import "./laborOptimization.css";

const laToday=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Los_Angeles",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const monthStart=(date)=>`${date.slice(0,7)}-01`;
const schoolYearFor=(date)=>{const year=Number(date.slice(0,4)),month=Number(date.slice(5,7)),start=month>=7?year:year-1;return `${start}-${String(start+1).slice(-2)}`;};
const fmt=(value)=>value==null?"—":Number(value).toFixed(1);

export default function LaborOptimizationPage({supervisorPin}){
  const today=laToday(),[startDate,setStartDate]=useState(monthStart(today)),[endDate,setEndDate]=useState(today),[applied,setApplied]=useState({startDate:monthStart(today),endDate:today}),[dataset,setDataset]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState(null);
  useEffect(()=>{let live=true;setLoading(true);setError("");loadMonthlyScorecardDatasetWithRetry(supervisorPin,schoolYearFor(applied.startDate),monthStart(applied.startDate)).then((data)=>{if(live)setDataset(data);}).catch((err)=>{if(live)setError(err.message||"Labor data could not be loaded.");}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[supervisorPin,applied]);
  const result=useMemo(()=>dataset?buildLaborOptimization(dataset,monthStart(applied.startDate),applied.startDate,applied.endDate):null,[dataset,applied]),counts=useMemo(()=>({out:result?.recommendations.filter((row)=>row.status==="move-out").reduce((sum,row)=>sum+row.remove.length,0)||0,needed:result?.recommendations.filter((row)=>row.status==="add").reduce((sum,row)=>sum+row.add.length,0)||0,matched:result?.transfers.length||0,keep:result?.recommendations.filter((row)=>row.mplh!=null&&row.target.min!=null&&row.mplh>=row.target.min&&row.mplh<=row.target.max).length||0}),[result]);
  if(selected)return <MonthlySchoolScorecard card={selected} onBack={()=>setSelected(null)}/>;
  return <section className="labor-optimization"><div className="labor-heading"><div><span>STAFFING DECISIONS</span><h3>Labor Optimization</h3></div><div className="labor-date-controls"><label>Start Date<input type="date" value={startDate} onChange={(e)=>setStartDate(e.target.value)}/></label><label>End Date<input type="date" min={startDate} value={endDate} onChange={(e)=>setEndDate(e.target.value)}/></label><button type="button" onClick={()=>setApplied({startDate,endDate})} disabled={!startDate||!endDate||endDate<startDate}>Apply</button></div></div>
    {error&&<div className="monthly-alert error" role="alert">{error}</div>}{loading?<div className="monthly-scorecard-loading">Calculating staffing recommendations…</div>:result&&<><div className="labor-summary"><article><span>Workers to Move Out</span><strong>{counts.out}</strong></article><article><span>Workers Needed</span><strong>{counts.needed}</strong></article><article><span>Matched Transfers</span><strong>{counts.matched}</strong></article><article><span>Schools Within Target</span><strong>{counts.keep}</strong></article></div><div className="command-table-wrap"><table className="command-table labor-table"><thead><tr><th>School</th><th>MPLH</th><th>Target</th><th>Current Workers</th><th>Current Worker Hours</th><th>Recommended Worker Hours</th><th>Action</th><th></th></tr></thead><tbody>{result.recommendations.map((row)=><tr key={row.school.directory_id}><td><button className="labor-school-link" onClick={()=>setSelected(row.card)}>{row.school.school_name}</button></td><td>{fmt(row.mplh)}</td><td>{row.target.min==null?"—":`${row.target.min}–${row.target.max}`}</td><td>{row.workerCount}</td><td>{fmt(row.currentWorkerHours)}</td><td>{fmt(row.recommendedWorkerHours??row.currentWorkerHours)}</td><td><span className={`labor-action ${row.status}`}>{row.action}</span></td><td><button className="command-small-button" onClick={()=>setSelected(row.card)}>View Scorecard</button></td></tr>)}</tbody></table></div><section className="labor-transfers"><h4>Recommended Transfers</h4>{result.transfers.length?<table><thead><tr><th>From School</th><th>To School</th><th>Worker Hours</th><th>Reason / Status</th></tr></thead><tbody>{result.transfers.map((item,index)=><tr key={`${item.from.directory_id}-${item.to.directory_id}-${index}`}><td>{item.from.school_name}</td><td>{item.to.school_name}</td><td>{item.hours.toFixed(1)} hours</td><td>Surplus → Need</td></tr>)}</tbody></table>:<p>No exact-hour school-to-school matches for this period.</p>}{result.unmatchedNeeds.map((item,index)=><p key={`need-${index}`}><strong>{item.school.school_name}</strong> needs 1 × {item.hours.toFixed(1)}-hour worker — no matching surplus available.</p>)}{result.unmatchedSurplus.map((item,index)=><p key={`surplus-${index}`}><strong>{item.school.school_name}</strong> has 1 × {item.hours.toFixed(1)}-hour surplus — no matching need available.</p>)}</section></>}
  </section>;
}
