import {buildLaborOptimization,isMovableWorker} from "./laborOptimization";

const base={rates:[],labor_rates:[],labor_hours:[],cost_rows:[],meal_counts:[],schools:[],staffing:[],staffing_positions:[],production_rows:[]};
const production=(directoryId,meals)=>[{location_id:directoryId,production_date:"2026-09-01",meal_type:"lunch",meals_served:meals,item_name:"Chicken",mma_oz_eq:2,prepared:meals,served:meals}];
const school=(id,name,type)=>({directory_id:id,location_id:id+100,source_site_id:String(id),school_name:name,labor_type:type,enrollment:100,budget_labor_hours:20});
const position=(id,site,name,title,hours)=>({id,source_site_id:String(site),employee_name:name,classification_title:title,assigned_daily_hours:hours,active:true});

test("Willenberg uses the Elementary PREP 20–22 target",()=>{const willenberg={...school(1,"Willenberg Special Ed","special_ed"),source_site_id:"1195701"},dataset={...base,schools:[willenberg],staffing_positions:[position(1,"1195701","Manager","Food Service Manager I",8),position(2,"1195701","Senior","Senior Food Service Worker",6.5)],production_rows:production(1,300)};expect(buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01").recommendations[0].target).toEqual(expect.objectContaining({min:20,max:22}));});
test("only regular filled workers are movable",()=>{expect(isMovableWorker(position(1,1,"Worker","Food Services Worker",6))).toBe(true);expect(isMovableWorker(position(2,1,"Manager","Food Service Manager IV",8))).toBe(false);expect(isMovableWorker(position(3,1,"Senior","Senior Food Service Worker",6.5))).toBe(false);expect(isMovableWorker(position(4,1,"VACANT","Food Services Worker",6))).toBe(false);});
test("matches one actual worker once and improves both schools",()=>{const sender=school(1,"Sender HS","secondary"),receiver=school(2,"Receiver HS","secondary"),worker=position(3,1,"REAL WORKER","Food Services Worker",6),senderWorkers=Array.from({length:8},(_,index)=>position(10+index,1,`Sender ${index}`,"Food Services Worker",6)),receiverWorkers=Array.from({length:8},(_,index)=>position(30+index,2,`Receiver ${index}`,"Food Services Worker",6)),dataset={...base,schools:[sender,receiver],staffing_positions:[position(1,1,"Manager A","Food Service Manager IV",8),worker,...senderWorkers,position(2,2,"Manager B","Food Service Manager IV",8),...receiverWorkers],production_rows:[...production(1,1100),...production(2,1150)]};const result=buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01");expect(result.transfers).toHaveLength(1);expect(result.transfers[0]).toEqual(expect.objectContaining({hours:6}));expect(result.transfers[0].sendingProjectedMplh).toBeGreaterThan(result.transfers[0].sendingCurrentMplh);expect(result.transfers[0].receivingProjectedMplh).toBeLessThan(result.transfers[0].receivingCurrentMplh);expect(new Set(result.transfers.map((move)=>move.employee.id)).size).toBe(result.transfers.length);});
test("keeps staffing when no practical move improves both schools",()=>{const only=school(1,"Only HS","secondary"),dataset={...base,schools:[only],staffing_positions:[position(1,1,"Manager","Food Service Manager IV",8),position(2,1,"Worker","Food Services Worker",6)],production_rows:production(1,270)};const result=buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01");expect(result.transfers).toHaveLength(0);expect(result.recommendations[0].status).toBe("keep");});
