import {buildLaborOptimization,buildManualWhatIf,getEmployeeKey,isMovableWorker} from "./laborOptimization";

const base={rates:[],labor_rates:[],labor_hours:[],cost_rows:[],meal_counts:[],schools:[],staffing:[],staffing_positions:[],production_rows:[]};
const production=(directoryId,meals)=>[{location_id:directoryId,production_date:"2026-09-01",meal_type:"lunch",meals_served:meals,item_name:"Chicken",mma_oz_eq:2,prepared:meals,served:meals}];
const school=(id,name,type)=>({directory_id:id,location_id:id+100,source_site_id:String(id),school_name:name,labor_type:type,enrollment:100,budget_labor_hours:20});
const position=(id,locationId,name,title,hours,sourceSite=locationId)=>({id,location_id:locationId,source_site_id:String(sourceSite),employee_name:name,classification_title:title,assigned_daily_hours:hours,active:true});

test("Willenberg uses the Elementary PREP 20–22 target",()=>{const willenberg={...school(1,"Willenberg Special Ed","special_ed"),source_site_id:"1195701"},dataset={...base,schools:[willenberg],staffing_positions:[position(1,willenberg.location_id,"Manager","Food Service Manager I",8),position(2,willenberg.location_id,"Senior","Senior Food Service Worker",6.5)],production_rows:production(1,300)};expect(buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01").recommendations[0].target).toEqual(expect.objectContaining({min:20,max:22}));});
test("filled and vacant regular worker positions are movable",()=>{expect(isMovableWorker(position(1,1,"Worker","Food Services Worker",6))).toBe(true);expect(isMovableWorker(position(2,1,"Manager","Food Service Manager IV",8))).toBe(false);expect(isMovableWorker(position(3,1,"Senior","Senior Food Service Worker",6.5))).toBe(false);expect(isMovableWorker(position(4,1,"VACANT","Food Services Worker",6))).toBe(true);expect(isMovableWorker(position(5,1,"VACANT","Food Service Manager I",8))).toBe(false);});
test("uses current location assignment rather than imported source-site metadata",()=>{const bonita=school(1,"Bonita EL","elementary_prep"),dataset={...base,schools:[bonita],staffing_positions:[position(1,bonita.location_id,"Manager","Food Service Manager I",8,"old-site"),position(2,bonita.location_id,"Worker A","Food Services Worker",6,"old-site"),position(3,bonita.location_id,"Worker B","Food Services Worker",6.5,"old-site")],production_rows:production(1,250)};const row=buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01").recommendations[0];expect(row.workerCount).toBe(2);expect(row.currentWorkerHours).toBe(12.5);});
test("labels a vacant-position transfer without representing it as an employee",()=>{const sender=school(1,"Sender HS","secondary"),receiver=school(2,"Receiver HS","secondary"),vacancy=position(3,sender.location_id,"VACANT","Food Services Worker",6.5),dataset={...base,schools:[sender,receiver],staffing_positions:[position(1,sender.location_id,"Manager A","Food Service Manager IV",8),vacancy,position(4,sender.location_id,"Worker B","Food Services Worker",6),position(2,receiver.location_id,"Manager B","Food Service Manager IV",8),position(5,receiver.location_id,"Worker C","Food Services Worker",6)],production_rows:[...production(1,220),...production(2,540)]};const result=buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01");expect(result.vacantMovablePositions).toBe(1);expect(result.transfers[0]).toEqual(expect.objectContaining({isVacantPosition:true,employeeName:null,transferLabel:"Move VACANT 6.5-hour FSW position"}));});
test("matches one actual worker once and projects from budgeted hours",()=>{const sender=school(1,"Sender HS","secondary"),receiver=school(2,"Receiver HS","secondary"),worker=position(3,sender.location_id,"REAL WORKER","Food Services Worker",6),dataset={...base,schools:[sender,receiver],staffing_positions:[position(1,sender.location_id,"Manager A","Food Service Manager IV",8),worker,position(4,sender.location_id,"Worker B","Food Services Worker",6.5),position(2,receiver.location_id,"Manager B","Food Service Manager IV",8),position(5,receiver.location_id,"Worker C","Food Services Worker",6)],production_rows:[...production(1,220),...production(2,540)]};const result=buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01");expect(result.qualifyingSenders).toBe(1);expect(result.qualifyingReceivers).toBe(1);expect(result.transfers).toHaveLength(1);expect(result.transfers[0]).toEqual(expect.objectContaining({hours:6.5}));expect(result.transfers[0].sendingCurrentMplh).toBeCloseTo(11);expect(result.transfers[0].sendingProjectedMplh).toBeCloseTo(220/13.5);expect(result.transfers[0].receivingCurrentMplh).toBeCloseTo(27);expect(result.transfers[0].receivingProjectedMplh).toBeCloseTo(540/26.5);expect(new Set(result.transfers.map((move)=>move.employee.id)).size).toBe(result.transfers.length);});
test("keeps schools at or inside the six MPLH intervention boundary",()=>{const prep=school(1,"Prep EL","elementary_prep"),make=(meals)=>({...base,schools:[prep],staffing_positions:[position(1,prep.location_id,"Manager","Food Service Manager I",8),position(2,prep.location_id,"Worker","Food Services Worker",6)],production_rows:production(1,meals)});expect(buildLaborOptimization(make(280),"2026-09-01","2026-09-01","2026-09-01").qualifyingSenders).toBe(0);expect(buildLaborOptimization(make(560),"2026-09-01","2026-09-01","2026-09-01").qualifyingReceivers).toBe(0);});
test("keeps staffing when no practical move improves both schools",()=>{const only=school(1,"Only HS","secondary"),dataset={...base,schools:[only],staffing_positions:[position(1,only.location_id,"Manager","Food Service Manager IV",8),position(2,only.location_id,"Worker","Food Services Worker",6)],production_rows:production(1,270)};const result=buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01");expect(result.transfers).toHaveLength(0);expect(result.recommendations[0].status).toBe("keep");});

test("uses meal equivalents over budgeted hours and ignores labor adjustments",()=>{const prep={...school(1,"Example EL","elementary_prep"),budget_labor_hours:27},dataset={...base,schools:[prep],staffing_positions:[position(1,prep.location_id,"Manager","Food Service Manager I",8),position(2,prep.location_id,"Worker","Food Services Worker",6)],production_rows:production(1,833),labor_hours:[{location_id:prep.location_id,service_date:"2026-09-01",additional_worker_hours:30,manager_overtime_hours:10}]};const row=buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01").recommendations[0];expect(row.mplh).toBeCloseTo(833/27);expect(row.baselineDailyHours).toBe(27);});

test("manual what-if projects both schools without mutating staffing",()=>{const from={...school(1,"From EL","elementary_prep"),budget_labor_hours:27},to={...school(2,"To EL","elementary_prep"),budget_labor_hours:27},worker=position(3,from.location_id,"Worker","Food Services Worker",6),dataset={...base,schools:[from,to],staffing_positions:[worker,position(4,to.location_id,"Other Worker","Food Services Worker",6.5)],production_rows:[...production(1,833),...production(2,833)]},snapshot=JSON.stringify(dataset.staffing_positions),result=buildLaborOptimization(dataset,"2026-09-01","2026-09-01","2026-09-01"),simulation=buildManualWhatIf(result,from.location_id,getEmployeeKey(worker),to.location_id);expect(simulation.fromCurrentMplh).toBeCloseTo(833/27);expect(simulation.fromProjectedMplh).toBeCloseTo(833/21);expect(simulation.toCurrentMplh).toBeCloseTo(833/27);expect(simulation.toProjectedMplh).toBeCloseTo(833/33);expect(JSON.stringify(dataset.staffing_positions)).toBe(snapshot);});
