import React from "react";
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,ReferenceLine} from "recharts";

const integer=(value)=>Math.round(Number(value)||0).toLocaleString();
const decimal=(value,digits=1)=>value===null||value===undefined?"—":Number(value).toFixed(digits);
const money=(value)=>value===null||value===undefined?"—":Number(value).toLocaleString("en-US",{style:"currency",currency:"USD"});
const change=(value,suffix="")=>value===null||value===undefined?"Baseline":`${value>=0?"+":""}${value.toFixed(1)}${suffix} vs prior month`;

function MealCard({label,total,average,participation,delta}){return <article className="scorecard-meal-card"><span>{label}</span><strong>{integer(total)}</strong><small>{decimal(average)} average/day</small>{participation!==undefined&&<div><b>{decimal(participation)}%</b> participation<em>{change(delta," pp")}</em></div>}</article>}
function Metric({label,value,note}){return <div className="scorecard-metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}

export default function MonthlySchoolScorecard({card,onBack}){
  const {school,current,previous,changes,summary}=card;
  return <div className="monthly-school-scorecard">
    <button type="button" className="scorecard-back" onClick={onBack}>← All schools</button>
    <header className="scorecard-header"><div><span>MONTHLY SCHOOL PERFORMANCE</span><h3>{school.school_name}</h3><p>Location {school.location_code||"Not assigned"} · {current.month.slice(0,7)} · {school.site_type||"Site type unavailable"}</p></div><div className="scorecard-header-facts"><Metric label="Enrollment" value={school.enrollment?integer(school.enrollment):"Not available"}/><Metric label="Operating days" value={current.operatingDays}/><Metric label="MPLH target" value={current.target.min===null?"Not assigned":`${current.target.min}–${current.target.max}`}/></div></header>
    <section><h4>Monthly meal snapshot</h4><div className="scorecard-meal-grid"><MealCard label="Breakfast" total={current.totals.breakfast} average={current.averages.breakfast} participation={current.participation.breakfast} delta={changes.breakfastParticipation}/><MealCard label="Lunch" total={current.totals.lunch} average={current.averages.lunch} participation={current.participation.lunch} delta={changes.lunchParticipation}/><MealCard label="Supper" total={current.totals.supper} average={current.averages.supper}/></div></section>
    {previous&&<section><h4>Previous-month comparison</h4><div className="scorecard-comparison-grid"><Metric label="Total meal change" value={`${changes.totalMeals>=0?"+":""}${integer(changes.totalMeals)}`}/><Metric label="Food cost/meal change" value={changes.foodCostPerMeal===null?"—":`${changes.foodCostPerMeal>=0?"+":"-"}${money(Math.abs(changes.foodCostPerMeal))}`}/><Metric label="Revenue change" value={changes.revenue===null?"—":`${changes.revenue>=0?"+":"-"}${money(Math.abs(changes.revenue))}`}/><Metric label="MPLH change" value={decimal(changes.mplh)}/></div></section>}
    <div className="scorecard-two-column"><section className="scorecard-panel"><h4>Daily lunch participation</h4>{current.lunchTrend.some((row)=>row.participation!==null)?<div className="scorecard-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={current.lunchTrend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={(v)=>v.slice(5)} fontSize={11}/><YAxis unit="%" fontSize={11}/><Tooltip formatter={(v)=>[`${Number(v).toFixed(1)}%`,"Lunch participation"]}/><ReferenceLine y={current.lunchAverage} stroke="#e5962d" strokeDasharray="5 4"/><Line type="monotone" dataKey="participation" stroke="#16855b" strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer></div>:<p className="scorecard-empty">Enrollment and meal data are required for this chart.</p>}</section>
      <section className="scorecard-panel"><h4>MPLH and labor</h4><div className="scorecard-metrics-grid"><Metric label="Average MPLH" value={decimal(current.averageMplh)} note={change(changes.mplh)}/><Metric label="Labor hours" value={decimal(current.laborHours)}/><Metric label="Days meeting target" value={current.daysMeetingTarget??"—"}/><Metric label="Days below target" value={current.daysBelowTarget??"—"}/></div></section></div>
    <div className="scorecard-two-column"><section className="scorecard-panel"><h4>Food cost and revenue</h4><div className="scorecard-cost-list"><div><span>Breakfast food cost</span><strong>{money(current.costs.breakfast)}</strong></div><div><span>Lunch food cost</span><strong>{money(current.costs.lunch)}</strong></div><div><span>Supper food cost</span><strong>{money(current.costs.supper)}</strong></div><div className="total"><span>Total food cost</span><strong>{money(current.totalCost)}</strong></div><div><span>Food cost per meal</span><strong>{money(current.foodCostPerMeal)}</strong></div><div><span>Meal revenue</span><strong>{money(current.revenue)}</strong></div></div><p className="scorecard-disclosure">Operating Margin is not shown because SPARK does not currently have a defensible labor-dollar rate mapping.</p></section>
      <section className="scorecard-panel"><h4>Menu and production</h4>{current.menuPerformance?<div className="scorecard-menu-highlight"><span>{current.menuPerformance.label}</span><strong>{current.menuPerformance.name}</strong>{current.menuPerformance.served!==null&&<small>{integer(current.menuPerformance.served)} portions served</small>}</div>:<p className="scorecard-empty">No reliable entrée or menu-plan result is available.</p>}<div className="scorecard-production-grid"><Metric label="Planned portions" value={integer(current.productionTotals.planned)}/><Metric label="Prepared portions" value={integer(current.productionTotals.prepared)}/><Metric label="Served portions" value={integer(current.productionTotals.served)}/><Metric label="Recorded leftover portions" value={integer(current.productionTotals.leftover)}/></div><p className="scorecard-disclosure">Portion totals reflect production-report item rows. No waste percentage is inferred.</p></section></div>
    <section><h4>Manager summary</h4><div className="scorecard-summary-grid">{Object.entries(summary).map(([label,text])=><article key={label}><span>{label}</span><p>{text}</p></article>)}</div></section>
    {!previous&&<div className="monthly-alert success">This is the first available month, so it is shown as the comparison baseline.</div>}
  </div>;
}
