import {buildSchoolScorecard,isLikelyEntree} from "./monthlyScorecardCalculations";

const school={directory_id:1,location_id:10,school_name:"CARSON HS",location_code:"8575",enrollment:100,budget_labor_hours:10,labor_type:"secondary"};
const dataset={rates:[{meal_type:"breakfast",rate:4.08},{meal_type:"lunch",rate:5.9},{meal_type:"supper",rate:5.9}],meal_counts:[],labor_hours:[],cost_rows:[{location_id:1,production_date:"2026-09-01",meal_type:"breakfast",food_cost:50},{location_id:1,production_date:"2026-09-01",meal_type:"lunch",food_cost:100}],production_rows:[
  {location_id:1,production_date:"2026-09-01",meal_type:"breakfast",meals_served:50,item_name:"Bean Burrito",mma_oz_eq:1,served:45,planned:50,prepared:50,leftover:5},
  {location_id:1,production_date:"2026-09-01",meal_type:"lunch",meals_served:80,item_name:"Milk White",mma_oz_eq:0,served:75,planned:80,prepared:80,leftover:5},
  {location_id:1,production_date:"2026-09-01",meal_type:"lunch",meals_served:80,item_name:"Chicken Sandwich",mma_oz_eq:2,served:70,planned:75,prepared:75,leftover:5},
]};

test("calculates participation, revenue, costs and production",()=>{const card=buildSchoolScorecard(school,dataset,"2026-09-01");expect(card.current.operatingDays).toBe(1);expect(card.current.participation.lunch).toBe(80);expect(card.current.totalCost).toBe(150);expect(card.current.revenues.lunch).toBeCloseTo(472);expect(card.current.revenue).toBeCloseTo(676);expect(card.current.menuRankings.lunch[0]).toEqual(expect.objectContaining({name:"Chicken Sandwich",served:70}));expect(card.current.productionTotals.leftoverPercentage).toBeCloseTo(15/205*100);expect(card.current.weekly[0]).toEqual(expect.objectContaining({prepared:205,served:190,leftover:15}));expect(card.summary.goal).toContain("Keep lunch participation at or above 80%");expect(card.current.operatingMargin).toBeNull();});

test("does not fabricate a complete food cost when a served meal has no cost rows",()=>{const withSupper={...dataset,production_rows:[...dataset.production_rows,{location_id:1,production_date:"2026-09-01",meal_type:"supper",meals_served:10,item_name:"Dinner entree",mma_oz_eq:2,served:10,planned:10,prepared:10,leftover:0}]};const card=buildSchoolScorecard(school,withSupper,"2026-09-01");expect(card.current.costAvailable.supper).toBe(false);expect(card.current.totalCost).toBeNull();expect(card.current.foodCostPerMeal).toBeNull();expect(card.current.recordedFoodCost).toBe(150);});
test("does not classify components as entrees",()=>{expect(isLikelyEntree({item_name:"Chocolate Milk",mma_oz_eq:2})).toBe(false);expect(isLikelyEntree({item_name:"Chicken Sandwich",mma_oz_eq:2})).toBe(true);});
