import React from "react";
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,ReferenceLine} from "recharts";

const integer=(value)=>value===null||value===undefined?"—":Math.round(Number(value)).toLocaleString();
const decimal=(value,digits=1)=>value===null||value===undefined?"—":Number(value).toFixed(digits);
const money=(value)=>value===null||value===undefined?"Unavailable":Number(value).toLocaleString("en-US",{style:"currency",currency:"USD"});
const readableDate=(value)=>value?new Date(`${value}T12:00:00`).toLocaleDateString("en-US",{month:"long",day:"numeric"}):"No service dates";
const readableMonth=(value)=>new Date(`${String(value).slice(0,7)}-01T12:00:00`).toLocaleDateString("en-US",{month:"long",year:"numeric"});
const signed=(value,suffix="")=>value===null||value===undefined?"Baseline":`${value>=0?"+":""}${Number(value).toFixed(1)}${suffix}`;

function MealKpi({meal,total,average,participation,delta,priorLabel}){
  return <article className={`scorecard-meal-kpi ${meal.toLowerCase()}`}><div className="scorecard-kpi-heading"><span>{meal}</span><small>Total meals</small></div><strong>{integer(total)}</strong><div className="scorecard-kpi-footer"><span><b>{decimal(average)}</b> avg/day</span>{participation!==undefined&&<span><b>{decimal(participation)}%</b> participation <em>{signed(delta," pp")}{priorLabel?` vs ${priorLabel}`:""}</em></span>}</div></article>;
}
function CompactMetric({label,value,note,tone="default"}){return <div className={`scorecard-compact-metric ${tone}`}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function FinanceRow({label,value,unavailable=false}){return <div className={unavailable?"unavailable":""}><span>{label}</span><strong>{unavailable?"Unavailable":money(value)}</strong></div>}

export default function MonthlySchoolScorecard({card,onBack}){
  const {school,current,previous,changes,summary}=card;
  const currentMonth=readableMonth(current.month),previousMonth=previous?readableMonth(previous.month):null;
  const menuItems=current.menuPerformance?.topItems||[];
  return <div className="monthly-school-scorecard scorecard-sheet">
    <div className="scorecard-toolbar"><button type="button" className="scorecard-back" onClick={onBack}>← All schools</button><span>On-screen scorecard · PDF preview format</span></div>
    <header className="scorecard-sheet-header"><div><span className="scorecard-eyebrow">MONTHLY SCHOOL PERFORMANCE SCORECARD</span><h3>{school.school_name}</h3><p>Location {school.location_code||"Not assigned"} · {school.site_type||"Site type unavailable"}</p></div><div className="scorecard-period"><strong>{currentMonth}</strong><span>Month-to-Date through {readableDate(current.dataThrough)}</span></div><div className="scorecard-enrollment"><span>Enrollment</span><strong>{school.enrollment?integer(school.enrollment):"Unavailable"}</strong><small>{current.operatingDays} operating days</small></div></header>

    <section className="scorecard-section scorecard-meals-section"><div className="scorecard-section-title"><div><span>01</span><h4>Meal participation</h4></div>{previous&&<small>Compared with {previousMonth}</small>}</div><div className="scorecard-meal-kpis"><MealKpi meal="Breakfast" total={current.totals.breakfast} average={current.averages.breakfast} participation={current.participation.breakfast} delta={changes.breakfastParticipation} priorLabel={previousMonth?.split(" ")[0]}/><MealKpi meal="Lunch" total={current.totals.lunch} average={current.averages.lunch} participation={current.participation.lunch} delta={changes.lunchParticipation} priorLabel={previousMonth?.split(" ")[0]}/><MealKpi meal="Supper" total={current.totals.supper} average={current.averages.supper}/></div></section>

    <div className="scorecard-middle-grid"><section className="scorecard-section scorecard-chart-panel"><div className="scorecard-section-title"><div><span>02</span><h4>Lunch participation trend</h4></div><small>Average {decimal(current.lunchAverage)}%</small></div>{current.lunchTrend.some((row)=>row.participation!==null)?<div className="scorecard-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={current.lunchTrend} margin={{top:8,right:10,left:-18,bottom:0}}><CartesianGrid stroke="#e6ece9" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={(v)=>v.slice(5).replace("-","/")} tick={{fontSize:10,fill:"#66766e"}} axisLine={false} tickLine={false}/><YAxis unit="%" tick={{fontSize:10,fill:"#66766e"}} axisLine={false} tickLine={false}/><Tooltip formatter={(v)=>[`${Number(v).toFixed(1)}%`,"Lunch participation"]} labelFormatter={(v)=>readableDate(v)}/><ReferenceLine y={current.lunchAverage} stroke="#e5962d" strokeDasharray="5 4"/><Line type="monotone" dataKey="participation" stroke="#16855b" strokeWidth={2.5} dot={{r:3,fill:"#fff",strokeWidth:2}} activeDot={{r:5}}/></LineChart></ResponsiveContainer></div>:<p className="scorecard-empty">Enrollment and meal data are required for this chart.</p>}</section>
      <section className="scorecard-section scorecard-mplh-panel"><div className="scorecard-section-title"><div><span>03</span><h4>MPLH & labor</h4></div><small>{current.target.min===null?"Target unavailable":`Target ${current.target.min}–${current.target.max}`}</small></div><div className="scorecard-mplh-hero"><div><span>Average MPLH</span><strong>{decimal(current.averageMplh)}</strong><small>{signed(changes.mplh)} vs {previousMonth||"prior month"}</small></div><div className="scorecard-target-track"><span style={{width:current.averageMplh===null?"0%":`${Math.min(100,current.averageMplh/Math.max(current.target.max||25,25)*100)}%`}}/><i style={{left:`${Math.min(100,(current.target.min||0)/Math.max(current.target.max||25,25)*100)}%`}}/></div></div><div className="scorecard-mini-grid"><CompactMetric label="Labor hours" value={decimal(current.laborHours)}/><CompactMetric label="Met target" value={current.daysMeetingTarget??"—"} note="days" tone="good"/><CompactMetric label="Below target" value={current.daysBelowTarget??"—"} note="days" tone={current.daysBelowTarget>0?"watch":"good"}/></div></section></div>

    <div className="scorecard-operations-grid"><section className="scorecard-section scorecard-menu-panel"><div className="scorecard-section-title"><div><span>04</span><h4>Menu performance</h4></div></div>{current.menuPerformance?<><div className="scorecard-top-entree"><span>{current.menuPerformance.label}</span><strong>{current.menuPerformance.name}</strong><small>{current.menuPerformance.served!==null?`${integer(current.menuPerformance.served)} portions served`:"From the recorded menu plan"}</small></div>{menuItems.length>1&&<div className="scorecard-menu-rankings">{menuItems.slice(1,3).map((item,index)=><div key={item.name}><span>{index+2}</span><p><strong>{item.name}</strong><small>{integer(item.served)} served</small></p></div>)}</div>}</>:<p className="scorecard-empty">No reliable entrée or menu-plan result is available.</p>}</section>
      <section className="scorecard-section scorecard-production-panel"><div className="scorecard-section-title"><div><span>05</span><h4>Production</h4></div><small>Recorded item portions</small></div><div className="scorecard-production-strip"><CompactMetric label="Planned" value={integer(current.productionTotals.planned)}/><CompactMetric label="Prepared" value={integer(current.productionTotals.prepared)}/><CompactMetric label="Served" value={integer(current.productionTotals.served)}/><CompactMetric label="Leftover" value={integer(current.productionTotals.leftover)}/></div><p className="scorecard-footnote">No waste percentage is inferred from these production-record totals.</p></section></div>

    <section className="scorecard-section scorecard-financial-panel"><div className="scorecard-section-title"><div><span>06</span><h4>Financial snapshot</h4></div><small>Estimated meal revenue at approved rates</small></div><div className="scorecard-financial-grid"><div><h5>Food cost</h5><FinanceRow label="Breakfast" value={current.costs.breakfast} unavailable={!current.costAvailable.breakfast}/><FinanceRow label="Lunch" value={current.costs.lunch} unavailable={!current.costAvailable.lunch}/><FinanceRow label="Supper" value={current.costs.supper} unavailable={!current.costAvailable.supper}/><FinanceRow label="Total food cost" value={current.totalCost} unavailable={current.totalCost===null}/><FinanceRow label="Food cost / meal" value={current.foodCostPerMeal} unavailable={current.foodCostPerMeal===null}/></div><div><h5>Meal revenue</h5><FinanceRow label="Breakfast · $4.08" value={current.revenues.breakfast}/><FinanceRow label="Lunch · $5.90" value={current.revenues.lunch}/><FinanceRow label="Supper · $5.90" value={current.revenues.supper}/><FinanceRow label="Total meal revenue" value={current.revenue}/></div></div>{!current.hasCompleteCost&&<p className="scorecard-data-note">Total food cost and food cost per meal are unavailable because a served meal has no corresponding source cost rows.</p>}</section>

    <section className="scorecard-management"><div className="scorecard-section-title"><div><span>07</span><h4>Management focus</h4></div></div><div className="scorecard-summary-grid">{Object.entries(summary).map(([label,text])=><article key={label} className={label}><span>{label}</span><p>{text}</p></article>)}</div></section>
    {!previous&&<div className="monthly-alert success">This is the first available month and is shown as the comparison baseline.</div>}
  </div>;
}
