import React,{useState,useMemo,useEffect} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {loadMplhReportData} from '../mplhReport/mplhReportService';
import {MEALS,rangeStart,buildMealAnalytics,summarize,comparisonRows} from './model';
import './mealAnalytics.css';
const colors={breakfast:'#ae6900',lunch:'#1874c9',supper:'#8853b7',total:'#174b49'};
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});
const money=n=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
const label=s=>s[0].toUpperCase()+s.slice(1);
const dateLabel=date=>new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'});
function Graph({rows,lines,currency=false}){return <div className="ma-graph" role="img" aria-label={`${currency?'Estimated reimbursement':'Meals'} by operating day: ${lines.map(l=>l.name).join(', ')}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{top:10,right:20,left:10,bottom:10}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tickFormatter={dateLabel} minTickGap={25}/><YAxis width={70} tickFormatter={n=>currency?`$${fmt(n)}`:fmt(n)}/><Tooltip labelFormatter={dateLabel} formatter={v=>currency?money(v):fmt(v)}/><Legend/>{lines.map(l=><Line key={l.key} type="bumpX" dataKey={l.key} name={l.name} stroke={l.color} strokeWidth={3} dot={false} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>;}
const average=n=>n===null?'—':Number(n).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1});
const count=n=>n===null?'—':fmt(n);
function Summary({days,name}){const totals=summarize(days);return <section className="ma-card"><h3>{name}</h3><p>{days.length} operating days · Selected range</p><div className="ma-metrics"><div><span>Total meals</span><strong>{fmt(totals.total)}</strong></div><div><span>Average meals / day</span><strong>{average(totals.stats.total.average)}</strong></div><div><span>Daily low / high</span><strong>{count(totals.stats.total.low)} / {count(totals.stats.total.high)}</strong></div><div><span>Estimated reimbursement</span><strong>{money(totals.revenue)}</strong></div></div><div className="ma-table-scroll"><table><thead><tr><th>Meal</th><th>Total meals</th><th>Avg / day</th><th>Daily low</th><th>Daily high</th><th>Participation</th><th>Reimbursement</th></tr></thead><tbody>{MEALS.map(m=><tr key={m}><th>{label(m)}</th><td>{fmt(totals[m])}</td><td>{average(totals.stats[m].average)}</td><td>{count(totals.stats[m].low)}</td><td>{count(totals.stats[m].high)}</td><td>{totals.stats[m].participation===null?'—':`${average(totals.stats[m].participation)}%`}</td><td>{money(totals[`${m}Revenue`])}</td></tr>)}</tbody></table></div><small>Daily figures include zero-meal operating days. Participation uses meals ÷ enrolled students across operating days; shown as — when enrollment is unavailable.</small></section>;}
export default function SupervisorMealAnalytics({schools,supervisorPin,endDate,setEndDate,refreshKey,rates}){
 const [tab,setTab]=useState('overall'),[preset,setPreset]=useState('30'),[customStart,setCustomStart]=useState(rangeStart('30',endDate));
 const [schoolId,setSchoolId]=useState(''),[secondId,setSecondId]=useState(''),[unit,setUnit]=useState('meals'),[metric,setMetric]=useState('total'),[combined,setCombined]=useState(true);
 const [visible,setVisible]=useState([...MEALS,'total']),[dataset,setDataset]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const schoolList=useMemo(()=>schools.filter(s=>s.school_name?.trim().toLowerCase()!=='test high school').slice().sort((a,b)=>a.school_name.localeCompare(b.school_name)),[schools]);
 const first=schoolList.find(s=>String(s.id)===schoolId)||schoolList[0];
 const second=schoolList.find(s=>String(s.id)===secondId&&s.id!==first?.id)||schoolList.find(s=>s.id!==first?.id);
 const startDate=preset==='custom'?customStart:rangeStart(preset,endDate);
 useEffect(()=>{let active=true;if(!startDate||!endDate||startDate>endDate||!schoolList.length)return;setLoading(true);setError('');setDataset(null);
 loadMplhReportData(supervisorPin,schoolList.map(s=>s.id),startDate,endDate).then(data=>{if(active)setDataset(data);}).catch(e=>{if(active)setError(e.message||'Could not load meal analytics');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[schoolList,supervisorPin,startDate,endDate,refreshKey]);
 const model=useMemo(()=>dataset?buildMealAnalytics({schools:schoolList,...dataset,startDate,endDate,rates}):null,[dataset,schoolList,startDate,endDate,rates]);
 const left=model?.schools.find(s=>s.school.id===first?.id)?.days||[],right=model?.schools.find(s=>s.school.id===second?.id)?.days||[];
 const days=tab==='overall'?model?.overall||[]:left,currency=unit==='reimbursement';
 const dataKey=m=>currency?(m==='total'?'revenue':`${m}Revenue`):m;
 const invalid=!startDate||!endDate||startDate>endDate;
 return <div className="ma-root"><section className="ma-card"><h2>Meal Analytics</h2><p>Operating days only. Meal Audit is the primary source; zero or missing audit counts use Finish Line. If both are zero, the result stays zero.</p><div className="ma-tabs" role="tablist" aria-label="Meal analytics views">{[['overall','All Schools'],['school','By School'],['compare','Compare Schools']].map(([id,name])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{name}</button>)}</div><div className="ma-filters"><label>Date range<select value={preset} onChange={e=>setPreset(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="month">Month to date</option><option value="school-year">School year to date</option><option value="custom">Custom range</option></select></label><label>From<input type="date" value={startDate} onChange={e=>{setCustomStart(e.target.value);setPreset('custom');}}/></label><label>Through<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label>Chart shows<select value={unit} onChange={e=>setUnit(e.target.value)}><option value="meals">Meals</option><option value="reimbursement">Reimbursement</option></select></label></div><small>Estimated reimbursement uses the existing SPARK rates: Breakfast {money(rates.breakfast)}, Lunch {money(rates.lunch)}, Supper {money(rates.supper)} per meal.</small></section>
 {invalid?<p role="alert">Choose a valid date range with the start on or before the end.</p>:error?<p role="alert" className="ma-error">{error}</p>:loading?<p role="status">Loading operating-day analytics…</p>:model&&<div className={tab==='school'?'ma-layout':''}>
 {tab==='school'&&<nav className="ma-school-list" aria-label="Choose a school">{schoolList.map(s=><button key={s.id} aria-pressed={first?.id===s.id} onClick={()=>setSchoolId(String(s.id))}>{s.school_name}</button>)}</nav>}
 <div className="ma-content">{tab==='compare'?<><section className="ma-card"><div className="ma-filters"><label><span className="ma-dot blue"/>School A<select value={first?.id||''} onChange={e=>setSchoolId(e.target.value)}>{schoolList.map(s=><option key={s.id} value={s.id}>{s.school_name}</option>)}</select></label><label><span className="ma-dot purple"/>School B<select value={second?.id||''} onChange={e=>setSecondId(e.target.value)}>{schoolList.filter(s=>s.id!==first?.id).map(s=><option key={s.id} value={s.id}>{s.school_name}</option>)}</select></label><label>Compare<select value={metric} onChange={e=>setMetric(e.target.value)}>{[...MEALS,'total'].map(m=><option key={m} value={m}>{label(m)}</option>)}</select></label><label className="ma-check"><input type="checkbox" checked={combined} onChange={e=>setCombined(e.target.checked)}/>Show both schools on one graph</label></div></section><div className="ma-comparison"><div className="ma-school-a"><Summary days={left} name={first?.school_name||'School A'}/>{!combined&&<Graph rows={left} currency={currency} lines={[{key:dataKey(metric),name:first?.school_name,color:'#1874c9'}]}/>}</div><div className="ma-school-b"><Summary days={right} name={second?.school_name||'School B'}/>{!combined&&<Graph rows={right} currency={currency} lines={[{key:dataKey(metric),name:second?.school_name,color:'#8853b7'}]}/>}</div></div>{combined&&<section className="ma-card"><h3>{label(metric)} comparison</h3><Graph rows={comparisonRows(left,right,dataKey(metric))} currency={currency} lines={[{key:'left',name:first?.school_name,color:'#1874c9'},{key:'right',name:second?.school_name,color:'#8853b7'}]}/></section>}</>:<><Summary days={days} name={tab==='overall'?'All Schools':first?.school_name||'School'}/><section className="ma-card"><h3>{currency?'Estimated Reimbursement':'Meal Counts'} by Operating Day</h3><div className="ma-toggles">{[...MEALS,'total'].map(m=><label key={m}><input type="checkbox" checked={visible.includes(m)} onChange={()=>setVisible(v=>v.includes(m)?v.filter(x=>x!==m):[...v,m])}/><span style={{color:colors[m]}}>{label(m)}</span></label>)}</div>{days.length?<Graph rows={days} currency={currency} lines={visible.map(m=>({key:dataKey(m),name:label(m),color:colors[m]}))}/>:<p>No operating days in this range.</p>}</section><details className="ma-card"><summary>Daily meals and reimbursement</summary><div className="ma-table-scroll"><table><thead><tr><th>Date</th>{MEALS.map(m=><th key={m}>{label(m)}</th>)}<th>Total</th><th>Reimbursement</th></tr></thead><tbody>{days.map(d=><tr key={d.date}><th>{dateLabel(d.date)}</th>{MEALS.map(m=><td key={m}>{fmt(d[m])}</td>)}<td>{fmt(d.total)}</td><td>{money(d.revenue)}</td></tr>)}</tbody></table></div></details></>}</div></div>}</div>;
}
