import React,{useCallback,useEffect,useMemo,useState}from"react";
import{STAFFING_GROUPS,isFixedStaff,loadStaffing,saveStaffingPosition,staffingGroupLabel}from"./staffingService";
import"./staffManagement.css";

const blank="";
export default function StaffManagementPage({supervisorPin}){
  const[data,setData]=useState({schools:[],positions:[]}),[selectedSchool,setSelectedSchool]=useState("all"),[query,setQuery]=useState(blank),[editingId,setEditingId]=useState(null),[draft,setDraft]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(blank),[message,setMessage]=useState(blank);
  const refresh=useCallback(async()=>{setLoading(true);setError(blank);try{setData(await loadStaffing(supervisorPin));}catch(e){setError(e.message||"Could not load staffing.");}finally{setLoading(false);}},[supervisorPin]);
  useEffect(()=>{refresh();},[refresh]);
  const schoolById=useMemo(()=>new Map(data.schools.map(s=>[String(s.id),s])),[data.schools]);
  const counts=useMemo(()=>{const m=new Map(data.schools.map(s=>[String(s.id),0]));data.positions.forEach(p=>m.set(String(p.location_id),(m.get(String(p.location_id))||0)+1));return m;},[data]);
  const positions=useMemo(()=>{const needle=query.trim().toLowerCase();return data.positions.filter(p=>{const school=schoolById.get(String(p.location_id));if(selectedSchool!=="all"&&String(p.location_id)!==selectedSchool)return false;if(!needle)return true;return[p.employee_name,p.employee_number,p.classification_title,school?.school_name,school?.location_code].some(v=>String(v||"").toLowerCase().includes(needle));});},[data.positions,query,schoolById,selectedSchool]);
  function edit(position){setEditingId(position.id);setDraft({...position,location_id:String(position.location_id)});setError(blank);setMessage(blank);}
  async function save(){const original=data.positions.find(p=>p.id===editingId);if(!draft?.employee_name?.trim()||!draft?.classification_title?.trim()){setError("Name and classification are required.");return;}const moved=String(original.location_id)!==String(draft.location_id);if(moved){const from=schoolById.get(String(original.location_id))?.school_name||"current school",to=schoolById.get(String(draft.location_id))?.school_name||"selected school";if(!window.confirm(`Move ${draft.employee_name} from ${from} to ${to}?`))return;}setSaving(true);setError(blank);try{await saveStaffingPosition(supervisorPin,draft);setMessage(moved?`${draft.employee_name} was reassigned.`:`${draft.employee_name} was updated.`);setEditingId(null);setDraft(null);await refresh();}catch(e){setError(e.message||"Could not save staffing changes.");}finally{setSaving(false);}}
  return <section className="staff-management">
    <div className="staff-toolbar"><div><h3>Staff Management</h3><p>Employee-level assignments from the September 1, 2026 PWI.</p></div><button type="button" className="command-refresh" onClick={refresh} disabled={loading}>↻ Refresh</button></div>
    <div className="staff-filters"><label>School<select value={selectedSchool} onChange={e=>setSelectedSchool(e.target.value)}><option value="all">All area schools</option>{data.schools.map(s=><option key={s.id} value={s.id}>{s.school_name} ({counts.get(String(s.id))||0})</option>)}</select></label><label>Find an employee<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, employee number, classification, or school"/></label></div>
    {message&&<div className="staff-message success">{message}</div>}{error&&<div className="staff-message error">{error}<button type="button" onClick={refresh}>Retry</button></div>}
    {loading?<div className="staff-loading">Loading staffing assignments…</div>:<div className="staff-school-list">
      {data.schools.filter(s=>selectedSchool==="all"||String(s.id)===selectedSchool).map(s=>{const rows=positions.filter(p=>String(p.location_id)===String(s.id));return <article className="staff-school" key={s.id}><header><div><span>Location {s.location_code}</span><h4>{s.school_name}</h4></div><strong>{rows.length} assigned</strong></header>{rows.length?<div className="staff-table-wrap"><table><thead><tr><th>Employee</th><th>Classification</th><th>Employee #</th><th>Hours</th><th>Position</th><th></th></tr></thead><tbody>{rows.map(p=>{const fixed=isFixedStaff(p);return <tr key={p.id}><td><b>{p.employee_name}</b></td><td>{p.classification_title}<small>{staffingGroupLabel(p.classification_key)}</small></td><td>{p.employee_number||"—"}</td><td>{Number(p.assigned_daily_hours).toFixed(1)}</td><td><span className={`staff-role ${fixed?"fixed":"movable"}`}>{fixed?"Fixed":"Worker"}</span></td><td><button type="button" className="staff-edit" onClick={()=>edit(p)}>Edit</button></td></tr>})}</tbody></table></div>:<p className="staff-empty">No matching assigned employees.</p>}</article>})}
    </div>}
    {editingId&&draft&&<div className="staff-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving){setEditingId(null);setDraft(null);}}}><div className="staff-modal" role="dialog" aria-modal="true" aria-label="Edit employee"><div className="staff-modal-head"><div><span>Edit employee</span><h3>{draft.employee_name}</h3></div><button type="button" onClick={()=>{setEditingId(null);setDraft(null);}} disabled={saving}>×</button></div><div className="staff-form"><label>Name<input value={draft.employee_name} onChange={e=>setDraft({...draft,employee_name:e.target.value})}/></label><label>Employee number<input value={draft.employee_number||blank} onChange={e=>setDraft({...draft,employee_number:e.target.value})}/></label><label>Classification/title<input value={draft.classification_title} onChange={e=>setDraft({...draft,classification_title:e.target.value})}/></label><label>Classification group<select value={draft.classification_key} onChange={e=>setDraft({...draft,classification_key:e.target.value})}>{STAFFING_GROUPS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Assigned daily hours<input type="number" min="0" max="24" step="0.25" value={draft.assigned_daily_hours} onChange={e=>setDraft({...draft,assigned_daily_hours:e.target.value})}/></label><label>Current school<select value={draft.location_id} disabled={!draft.movable} onChange={e=>setDraft({...draft,location_id:e.target.value})}>{data.schools.map(s=><option key={s.id} value={s.id}>{s.school_name}</option>)}</select></label><label className="staff-checkbox"><input type="checkbox" checked={Boolean(draft.movable)} onChange={e=>setDraft({...draft,movable:e.target.checked})}/><span>Allow school-to-school reassignment{isFixedStaff(draft)?" (fixed position override)":""}</span></label></div><div className="staff-modal-actions"><button type="button" onClick={()=>{setEditingId(null);setDraft(null);}} disabled={saving}>Cancel</button><button type="button" className="primary" onClick={save} disabled={saving}>{saving?"Saving…":"Save changes"}</button></div></div></div>}
  </section>;
}
