import React,{useEffect,useState} from 'react';
import {breakfastMenu,breakfastPacking} from './service';
import {PACKING_ITEMS} from './packingItems';
export const breakfastToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
// Menu is shared by the school; sent quantities belong to one classroom/date.
export default function BreakfastDispatch({token,record,onSaved}){
 const [date,setDate]=useState(breakfastToday),[values,setValues]=useState(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;setBusy(true);setValues(null);setError('');setMessage('');const request=record?breakfastPacking(token,record.id,date):breakfastMenu(token,date);request.then(v=>{if(active)setValues(v);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[token,record,date]);
 async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{setValues(record?await breakfastPacking(token,record.id,date,values):await breakfastMenu(token,date,values));setMessage(record?'Sent quantities saved.':'School menu saved.');onSaved?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const items=record?values?.items:values;
 return <details className="ba-dispatch"><summary>{record?'Meals / items sent':'School breakfast menu'}</summary><p>{record?'Enter the actual quantities packed for this classroom. Leave unknown quantities blank.':'Enter the menu for this school and service date. It appears on each classroom’s worker return screen.'}</p><label>Service date<input type="date" required disabled={busy} value={date} onChange={e=>setDate(e.target.value)}/></label>{error&&<p role="alert" className="ba-error">{error}</p>}{message&&<p role="status">{message}</p>}{values&&<form onSubmit={save} className="ba-form"><fieldset disabled={busy}><div className="ba-fields">{record&&<label>Meals sent<input type="number" min="0" max="10000" step="1" value={values.sent??''} onChange={e=>setValues({...values,sent:e.target.value===''?null:Number(e.target.value)})}/></label>}{PACKING_ITEMS.map(([k,label])=><label key={k}>{label}{record?' sent':' menu item'}<input type={record?'number':'text'} min={record?0:undefined} max={record?10000:undefined} step={record?1:undefined} maxLength={record?undefined:160} value={items[k]??''} onChange={e=>{const next={...items};if(record&&e.target.value==='')delete next[k];else next[k]=record?Number(e.target.value):e.target.value;setValues(record?{...values,items:next}:next);}}/></label>)}</div><button className="ba-primary">{busy?'Saving…':'Save'}</button></fieldset></form>}</details>;
}
