import React,{useRef,useState} from 'react';
const blank=id=>({id,values:{room_code:'',teacher_name:'',enrolled_students:'',campus_label:'',active:true},saved:false,error:''});
export default function ClassroomBatchForm({onSave,onCancel}){
 const next=useRef(1),saving=useRef(false);
 const [rows,setRows]=useState(()=>[blank(0)]),[count,setCount]=useState('10'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const update=(id,patch)=>setRows(old=>old.map(r=>r.id===id?{...r,...patch}:r));
 function addRows(){const n=Number(count);if(!Number.isInteger(n)||n<1||n>100){setError('Enter a whole number from 1 to 100.');return;}setError('');setRows(old=>[...old,...Array.from({length:Math.max(0,n-old.length)},()=>blank(next.current++))]);}
 async function save(e){e.preventDefault();if(saving.current)return;saving.current=true;setBusy(true);setError('');try{for(const row of rows.filter(r=>!r.saved)){
  const v=row.values;if(!v.room_code.trim()||!v.teacher_name.trim()||v.enrolled_students===''||!Number.isInteger(Number(v.enrolled_students))||Number(v.enrolled_students)<0||Number(v.enrolled_students)>1000){update(row.id,{error:'Enter a room, teacher, and student count from 0 to 1000.'});continue;}
  try{await onSave(v);update(row.id,{saved:true,error:''});}catch(e){update(row.id,{error:e.message||'Could not save this classroom. Please try again.'});}
 }}finally{saving.current=false;setBusy(false);}}
 const complete=rows.length>0&&rows.every(r=>r.saved);
 return <section className="ba-panel"><div className="ba-toolbar"><h2>Add classrooms</h2><label>Number of rows<input type="number" min="1" max="100" step="1" value={count} disabled={busy} onChange={e=>setCount(e.target.value)}/></label><button type="button" disabled={busy} onClick={addRows}>Submit</button></div><p>Enter one classroom per row. Choose a number above to show that many rows; existing entries stay in place.</p>{error&&<p role="alert" className="ba-error">{error}</p>}
 <form onSubmit={save}><div className="ba-table-scroll"><table className="ba-classroom-entry"><thead><tr><th>Room number / code</th><th>Teacher name</th><th>Enrolled students</th><th>Campus / offsite (optional)</th><th>Actions / status</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id}>{[['room_code','Room number / code',40],['teacher_name','Teacher name',160],['enrolled_students','Enrolled students'],['campus_label','Campus / offsite',120]].map(([key,label,max])=><td key={key}><input aria-label={`${label}, row ${i+1}`} type={key==='enrolled_students'?'number':'text'} required={key!=='campus_label'} min={key==='enrolled_students'?0:undefined} max={key==='enrolled_students'?1000:undefined} step={key==='enrolled_students'?1:undefined} maxLength={max} value={row.values[key]} disabled={busy||row.saved} onChange={e=>update(row.id,{values:{...row.values,[key]:e.target.value},error:''})}/></td>)}<td>{row.saved?<span role="status" className="ba-badge">Saved</span>:<button type="button" disabled={busy} aria-label={`Remove row ${i+1}`} onClick={()=>setRows(old=>old.filter(r=>r.id!==row.id))}>Remove</button>}{row.error&&<p role="alert" className="ba-warning">{row.error}</p>}</td></tr>)}</tbody></table></div>
 <div className="ba-actions ba-batch-actions"><button type="button" disabled={busy||rows.length>=100} onClick={()=>setRows(old=>[...old,blank(next.current++)])}>+ Add another row</button><button className="ba-primary" disabled={busy||!rows.length||complete}>{busy?'Saving classrooms…':'Save classrooms'}</button><button type="button" disabled={busy} onClick={onCancel}>{rows.some(r=>r.saved)?'Done':'Cancel'}</button></div><p className="ba-small">Saved classrooms stay saved. If a row needs correction, fix it and save again; saved rows will not be submitted again.</p></form></section>;
}
