import React,{useState} from 'react';
import QRCode from 'qrcode';
import {classroomQr,sendMessage} from './service';
import {teacherLink} from './TeacherPage';
export default function ClassroomTeacherTools({token,record,onMessage}){
 const [url,setUrl]=useState(''),[image,setImage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState('');
 const [values,setValues]=useState({body:'',delivery:'next_open',require_ack:false,expires_on:''});
 async function showQr(){setBusy(true);setError('');try{const link=teacherLink(await classroomQr(token,record.id));setUrl(link);setImage(await QRCode.toDataURL(link,{width:320,margin:4,errorCorrectionLevel:'M'}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function submit(e){e.preventDefault();setBusy(true);setError('');setSent('');try{await sendMessage(token,record.id,values);setValues({...values,body:''});setSent('Message saved for this classroom.');onMessage();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="ba-teacher-tools"><h3>Classroom QR & teacher messages</h3>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={showQr}>Show permanent classroom QR</button>{image&&<div className="ba-qr"><img src={image} alt={`Breakfast QR for room ${record.room_code}`}/><a href={url} target="_blank" rel="noreferrer">Open teacher page for Room {record.room_code}</a><p>Reuse this QR every day. Share only with this classroom; anyone with it can submit its teacher count before cutoff.</p></div>}
 <form onSubmit={submit} className="ba-form"><label>Message to this classroom<textarea required maxLength={2000} value={values.body} onChange={e=>setValues({...values,body:e.target.value})}/></label><label>Show message<select value={values.delivery} onChange={e=>setValues({...values,delivery:e.target.value})}><option value="next_open">Next time the QR opens (for that day)</option><option value="today">Today only</option><option value="until_ack">Until acknowledged</option><option value="expires">Through an expiration date</option></select></label>{values.delivery==='expires'&&<label>Expiration date<input type="date" required value={values.expires_on} onChange={e=>setValues({...values,expires_on:e.target.value})}/></label>}<label className="ba-check"><input type="checkbox" checked={values.require_ack||values.delivery==='until_ack'} disabled={values.delivery==='until_ack'} onChange={e=>setValues({...values,require_ack:e.target.checked})}/>Require acknowledgment</label><button className="ba-primary" disabled={busy||!values.body.trim()}>Send classroom message</button>{sent&&<p role="status">{sent}</p>}</form></section>;
}
