import React,{useEffect,useState} from 'react';
import {openSession,closeSession,finishLineTotal} from './service';
export function bicSummary(data){const rows=data?.rows||[];return {total:data?.total??0,reported:rows.filter(r=>r.record?.teacher_submitted_at&&r.record?.teacher_certified).length,rooms:rows.length};}
export default function FinishLineBreakfast({location,employee,managerPin,date,onUse,disabled}){
 const [token,setToken]=useState(''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[used,setUsed]=useState(false);
 useEffect(()=>{let active=true,session;setToken('');setData(null);setError('');setUsed(false);if(!managerPin)return;setBusy(true);(async()=>{try{session=await openSession(location,employee,managerPin);if(!active)return;const d=await finishLineTotal(session,date);if(active){setToken(session);setData(d);}}catch(e){if(active)setError(e.message);}finally{if(active)setBusy(false);if(!active&&session)closeSession(session).catch(()=>{});}})();return()=>{active=false;if(session)closeSession(session).catch(()=>{});};},[location,employee,managerPin,date]);
 async function refresh(){setBusy(true);setError('');setUsed(false);try{setData(await finishLineTotal(token,date));}catch(e){setError(e.message);setData(null);}finally{setBusy(false);}}
 const summary=bicSummary(data);
 if(!managerPin||(!busy&&!error&&!summary.rooms))return null;
 return <div style={{padding:14,marginBottom:16,background:'#edf6f3',borderRadius:10,fontSize:14}}><div style={{display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}><strong>BIC breakfast · {date}</strong><span aria-live="polite">{busy?'Loading…':data?`${summary.total} student meals`:'Count unavailable'}</span><button className={`yes-no-button ${used?'selected-good':''}`} style={{width:'auto',minHeight:44,padding:'8px 14px'}} type="button" title={summary.reported!==summary.rooms?'Waiting for all classroom counts':undefined} disabled={disabled||busy||!!error||!summary.rooms||summary.reported!==summary.rooms} onClick={()=>{onUse(String(summary.total));setUsed(true);}}>Use BIC total</button><button className="yes-no-button" style={{width:'auto',minHeight:44,padding:'8px 14px'}} type="button" disabled={disabled||busy||!token} onClick={refresh}>Refresh BIC total</button></div>{error&&<p role="alert">BIC total could not be loaded: {error}</p>}</div>;
}
