import React,{useEffect,useState} from 'react';
import {openSession,closeSession,dailyDashboard} from './service';
export function bicSummary(data){const rows=data?.rows||[];return {total:data?.total??0,reported:rows.filter(r=>r.record?.teacher_submitted_at&&r.record?.teacher_certified).length,rooms:rows.length};}
export default function FinishLineBreakfast({location,employee,managerPin,date,onUse,disabled}){
 const [token,setToken]=useState(''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[used,setUsed]=useState(false);
 useEffect(()=>{let active=true,session;setToken('');setData(null);setError('');setUsed(false);if(!managerPin)return;setBusy(true);(async()=>{try{session=await openSession(location,employee,managerPin);if(!active)return;const d=await dailyDashboard(session,date);if(active){setToken(session);setData(d);}}catch(e){if(active)setError(e.message);}finally{if(active)setBusy(false);if(!active&&session)closeSession(session).catch(()=>{});}})();return()=>{active=false;if(session)closeSession(session).catch(()=>{});};},[location,employee,managerPin,date]);
 async function refresh(){setBusy(true);setError('');setUsed(false);try{setData(await dailyDashboard(token,date));}catch(e){setError(e.message);setData(null);}finally{setBusy(false);}}
 const summary=bicSummary(data);
 if(!managerPin||(!busy&&!error&&!summary.rooms))return null;
 return <div style={{padding:14,marginBottom:16,background:'#edf6f3',borderRadius:10,fontSize:14}}><strong>BIC breakfast · {date}</strong>{busy?<p>Loading classroom counts…</p>:data&&<p>{summary.total} student meals · {summary.reported} of {summary.rooms} classrooms submitted.</p>}{error&&<p role="alert">BIC total could not be loaded: {error}</p>}<button type="button" disabled={disabled||busy||!!error||!summary.rooms||summary.reported!==summary.rooms} onClick={()=>{onUse(String(summary.total));setUsed(true);}}>Use BIC total</button> <button type="button" disabled={disabled||busy||!token} onClick={refresh}>Refresh BIC total</button><p>Copies the student total into Breakfast for this date. Adult meals are excluded. Check any breakfast served outside BIC before submitting Finish Line.</p>{summary.rooms>summary.reported&&<p>Wait for the remaining classrooms before using the total.</p>}{used&&<p role="status">Breakfast count filled. Review and submit Finish Line to save it.</p>}</div>;
}
