import React,{useEffect,useState} from 'react';
import {teacherPreorder} from './service';
export default function TeacherPreorder({qr,page,onSaved,onBusy}){
 const [entree,setEntree]=useState(page.record?.preorder_entree||''),[quantity,setQuantity]=useState(page.record?.preorder_count??''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(Boolean(page.record?.preorder_submitted_at&&page.record?.preorder_date===page.preorder_date));
 useEffect(()=>{setEntree(page.record?.preorder_entree||'');setQuantity(page.record?.preorder_count??'');setSaved(Boolean(page.record?.preorder_submitted_at&&page.record?.preorder_date===page.preorder_date));},[page.record?.preorder_revision,page.record?.preorder_entree,page.record?.preorder_count,page.record?.preorder_submitted_at,page.record?.preorder_date,page.preorder_date,page.service_date]);
 const label=new Date(page.preorder_date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'});
 async function submit(e){e.preventDefault();setBusy(true);onBusy(true);setError('');try{onSaved(await teacherPreorder(qr,page,entree,Number(quantity)));setSaved(true);}catch(e){setError(e.message);}finally{setBusy(false);onBusy(false);}}
 return <form className="ba-panel ba-form" onSubmit={submit}><h2>Pre-order for {label}</h2><p>Help us reduce waste—tell us which entrée and how many your class needs for the next breakfast.</p><div className="ba-fields"><label>Entrée<input required maxLength={120} disabled={busy} value={entree} onChange={e=>{setEntree(e.target.value);setSaved(false);}}/></label><label>Quantity<input required type="number" min="0" max="1000" step="1" disabled={busy} value={quantity} onChange={e=>{setQuantity(e.target.value);setSaved(false);}}/></label></div><button className="ba-primary" disabled={busy||!entree.trim()||quantity===''}>{busy?'Saving…':'Save pre-order'}</button>{saved&&<p role="status">Pre-order saved.</p>}{error&&<p role="alert">{error}</p>}</form>;
}
