import { MILK_FAT_TYPES, blankMilks } from "./model";
import React from "react";
import { DAYS, SERVICE_DAYS, serviceEnd, repeatedHistory, historyKey, monitoringDay, observedServices, countValid, attendanceKey, ZERO_HISTORY_MESSAGE, average, schoolYear, applicableQuestions, findings } from "./model";

function AttendanceWarning({ date, meals, attendance, confirmed, onConfirm, today = false }) {
  if (!countValid(meals) || !countValid(attendance) || Number(meals) !== Number(attendance)) return null;
  return <div className="sm-notice sm-attendance-warning"><p>Please double-check {today ? "the" : "this"} attendance. These numbers indicate that 100% of the program attendance participated in Supper. This can happen, but it is uncommon. Verify the attendance using the attendance and Community Roster.</p><label className="sm-check"><input type="checkbox" checked={confirmed === attendanceKey(date, meals, attendance)} onChange={e => onConfirm(e.target.checked ? attendanceKey(date, meals, attendance) : "")} />Confirm Numbers Are Correct</label></div>;
}
export default function GuidedSections({ section, data, change, field, Field, errors, showErrors, countOptions, historyWeek, location, slots, actionFields }) {
  function serviceChange(index, key, value) { change("serviceTimes", data.serviceTimes.map((row, i) => i === index ? { ...row, [key]: value, ...(key === "start" ? {end: serviceEnd(value)} : {}) } : row)); }
  function rowErrors(id) { return errors.filter(e => e.field === id).map((e,i) => <p className="sm-error" key={i}>{e.message}</p>); }
  if (section === 0) return <><p>Confirm the date and the time you arrived and left. Supper monitoring visits are always unannounced.</p><p><strong>{location.school_name}</strong> · {location.location_code}</p><div className="sm-grid"><Field id="monitoringDate" label="Monitoring date" type="date" value={data.monitoringDate} errors={errors} reveal={showErrors} onChange={value => { change("monitoringDate", value); change("schoolYear", schoolYear(value) || data.schoolYear); }} />{field("arrivalTime", "Arrival time", { type: "time", reveal: !!data.arrivalTime || showErrors })}{field("departureTime", "Departure time", { type: "time", reveal: !!data.departureTime || showErrors })}{field("schoolYear", "School year", { placeholder: "2026-27" })}<label>Monitoring slot<select value={data.monitoringSlot || ""} onChange={e => change("monitoringSlot", e.target.value)}>{Object.entries(slots).map(([slot,label]) => <option key={slot} value={slot}>{label}</option>)}</select></label></div>
    <h3>CDE-Approved Supper Service Times</h3><p>Add each After School Program and its day-specific approved hours. Select every service observed on the monitoring date{monitoringDay(data.monitoringDate) ? ` (${monitoringDay(data.monitoringDate)})` : ""}. Your visit must start before and end after all selected services.</p>
    {data.legacyServiceTime && <p className="sm-notice">Previously entered approved time: {data.legacyServiceTime}. Verify the copied times below against the CDE approval.</p>}
    <div className="sm-service-table"><div className="sm-service-heading"><span>After School Program Name</span><span>Day</span><span>Start Time</span><span>End Time</span><span>Observed</span><span /></div>{(data.serviceTimes || []).map((row,i) => <div className="sm-service-row" key={i}><Field id={`program-${i}`} label="After School Program Name" value={row.program} onChange={v => serviceChange(i,"program",v)} errors={errors} reveal={showErrors} /><label className="sm-service-day"><span>Day</span><select aria-label={`Day for service ${i+1}`} value={row.day} onChange={e => serviceChange(i,"day",e.target.value)}><option value="">Choose day</option>{SERVICE_DAYS.map(day => <option key={day}>{day}</option>)}</select>{showErrors && rowErrors(`day-${i}`)}</label><Field id={`start-${i}`} label="CDE-approved start time" type="time" value={row.start} onChange={v => serviceChange(i,"start",v)} errors={errors} reveal={showErrors} /><Field id={`end-${i}`} label="CDE-approved end time" type="time" value={serviceEnd(row.start)} readOnly errors={errors} reveal={showErrors} /><label className="sm-check"><input type="checkbox" aria-label={`Observed service ${i+1}`} disabled={row.day !== monitoringDay(data.monitoringDate)} checked={row.observed && row.day === monitoringDay(data.monitoringDate)} onChange={e => serviceChange(i,"observed",e.target.checked)} /><span>Observed</span></label><button type="button" aria-label={`Remove service ${i+1}`} onClick={() => change("serviceTimes", data.serviceTimes.filter((_,index) => i !== index))}>Remove</button>{row.needsConfirmation && <label className="sm-check sm-service-confirm"><input type="checkbox" onChange={() => serviceChange(i,"needsConfirmation",false)} />I verified this program, day and times against the CDE approval.</label>}</div>)}</div>
    <button type="button" onClick={() => change("serviceTimes", [...(data.serviceTimes || []), { program: "", day: monitoringDay(data.monitoringDate), start: "", end: "", observed: true }])}>+ Add Service Time</button>{showErrors && rowErrors("serviceTimes")}</>;
  if (section === 1) {
    const zero = data.history.some(day => countValid(day.meals) && Number(day.meals) === 0);
    return <><div className="sm-notice"><strong>5-DAY HISTORY</strong><ul><li>Select a complete Monday-Friday week.</li><li>Do not include the monitoring date.</li><li>Every selected day must have a Supper meal count greater than 0.</li><li>Attendance must be equal to or greater than the meal count.</li><li>Verify attendance using the attendance and Community Roster.</li></ul></div><Field id="weekStart" label="Choose a Monday–Friday week" type="date" value={data.weekStart} onChange={historyWeek} errors={errors} reveal={showErrors} />{zero && <div role="alert" className="sm-notice"><p>{ZERO_HISTORY_MESSAGE}</p><button type="button" onClick={() => document.getElementById("weekStart")?.focus()}>Select Different Week</button></div>}
      <div className="sm-history"><div className="sm-history-heading"><span>Day / Date</span><span>Supper Meal Count</span><span>Attendance</span></div>{data.history.map((day,index) => <React.Fragment key={day.date}><div className="sm-history-row"><strong>{DAYS[index]}<small>{day.date}</small></strong>{["meals","attendance"].map(key => <Field key={key} id={`${key}-${index}`} label={`${DAYS[index]} ${key === "meals" ? "Supper Meal Count" : "attendance"}`} value={day[key]} errors={errors} reveal={showErrors || (countValid(day.meals) && countValid(day.attendance))} {...countOptions} onChange={value => change("history",data.history.map((row,i) => i === index ? { ...row, [key]:value, attendanceConfirmed:"" } : row))} />)}</div>{Number(day.meals) > 0 && <AttendanceWarning {...day} confirmed={day.attendanceConfirmed} onConfirm={value => change("history",data.history.map((row,i) => i === index ? {...row,attendanceConfirmed:value} : row))} />}</React.Fragment>)}</div>{repeatedHistory(data.history) && <div className="sm-notice"><strong>Please double-check the 5-Day History.</strong><p>The meal counts and/or attendance are the same or very similar across several days. This may be correct, but repeated numbers can indicate that actual daily counts were not entered.</p><p>Verify each day's Supper Meal Count using the meal count records and verify attendance using the attendance and Community Roster.</p><label className="sm-check"><input type="checkbox" checked={data.historyVerified === historyKey(data.history)} onChange={e => change("historyVerified", e.target.checked ? historyKey(data.history) : "")} />I Verified These Numbers</label></div>}<p className="sm-summary">Five-day meal-count average: <strong>{average(data.history) === null ? "Enter all five meal counts" : average(data.history).toLocaleString()}</strong></p></>;
  }
  if (section === 2) return <><p><strong>Monitoring Date: {data.monitoringDate ? new Date(`${data.monitoringDate}T12:00:00`).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}) : "Choose a monitoring date"}</strong></p><p>Enter the meal count and attendance for the monitoring date.</p><p>After School Program: {observedServices(data).map(row => row.program).join(", ") || "Select observed services in Monitoring Information"}</p><div className="sm-grid">{field("todayMeals","Today's Supper Meal Count",countOptions)}{field("todayAttendance","Today's Attendance",{...countOptions,reveal:showErrors || (countValid(data.todayMeals) && countValid(data.todayAttendance))})}</div><AttendanceWarning today date={data.monitoringDate} meals={data.todayMeals} attendance={data.todayAttendance} confirmed={data.todayAttendanceConfirmed} onConfirm={value => change("todayAttendanceConfirmed",value)} /></>;
  if (section === 3) return <><p>* Required. Enter two different milk fat types and all five required components. Additional Meat/Alternate and Other may remain blank.</p><div className="sm-menu-table"><div className="sm-menu-heading"><span>Menu Item</span><span>Specific Food Used</span><span>Serving Size</span></div>{(data.milks || blankMilks()).map((milk,i)=><div className="sm-menu-row" key={`milk-${i}`}><strong>Milk {i+1} *</strong><div><label htmlFor={`milk-fat-${i}`}>Fat type<select id={`milk-fat-${i}`} aria-label={`Milk ${i+1} fat type`} value={milk.fatType} onChange={e=>change("milks",(data.milks||blankMilks()).map((m,n)=>n===i?{...m,fatType:e.target.value}:m))}><option value="">Choose fat type</option>{MILK_FAT_TYPES.map(type=><option key={type} value={type}>{type}</option>)}</select></label>{showErrors && errors.filter(e=>e.field===`milk-fat-${i}`).map(e=><p className="sm-error" key={e.message}>{e.message}</p>)}<Field id={`milk-description-${i}`} label="Description/Flavor" aria-label={`Milk ${i+1} description/flavor`} value={milk.description} errors={errors} reveal={showErrors} onChange={value=>change("milks",(data.milks||blankMilks()).map((m,n)=>n===i?{...m,description:value}:m))}/></div><Field id={`milk-serving-${i}`} label="Serving size" aria-label={`Milk ${i+1} serving size`} value={milk.serving} errors={errors} reveal={showErrors} onChange={value=>change("milks",(data.milks||blankMilks()).map((m,n)=>n===i?{...m,serving:value}:m))}/></div>)}{data.menu.slice(1).map((row,index) => {const i=index+1;return <div className="sm-menu-row" key={row.category}><strong>{row.category}{i<5?' *':' (Optional)'}</strong>{["item","serving"].map(key => <Field key={key} id={key === "item" ? `menu-${i}` : `serving-${i}`} label={key === "item" ? "Specific food used" : "Serving size"} aria-label={`${row.category} ${key === "item" ? "specific food used" : "serving size"}`} value={row.applicable ? row[key] : ""} errors={errors} reveal={showErrors} onChange={value => change("menu",data.menu.map((item,index) => index === i ? {...item,...(!item.applicable ? {item:"",serving:""} : {}),[key]:value,applicable:true} : item))} />)}</div>;})}</div></>;

  if (section === 4) return <><p>Answer the official monitoring questions below. Required follow-up fields appear with the applicable question. N/A is offered only where permitted by the official form.</p><div className="sm-question-list">{applicableQuestions(data).map(q => <section className="sm-question-row" key={q.id}><div className="sm-question-main"><div><strong>{q.id}.</strong> {q.text.replace(/\bASP\b/g,"After School Program").replace(/\bFSD\b/g,"Food Services Division")}{q.tip && <p className="sm-question-tip">{q.tip}</p>}</div><div role="group" aria-label={`Question ${q.id}`} className="sm-answers">{q.options.map(option => <button type="button" key={option} aria-pressed={data.answers[q.id] === option} onClick={() => change("answers",{...data.answers,[q.id]:option,...(q.id === "18a" && option === "no" ? {"18b":"na"} : {})})}>{option === "na" ? "N/A" : option === "yes" ? "Yes" : "No"}</button>)}</div></div>{showErrors && rowErrors(`question-${q.id}`)}{q.id === "18a" && data.answers["18a"] === "no" && <p>18b is marked N/A because 18a is No.</p>}{q.id === "20" && data.answers["20"] === "yes" && findings(data).length > 0 && <p className="sm-notice">You reported findings elsewhere. Review this overall assessment after documenting the corrective actions.</p>}{q.id === "18b" && data.answers["18b"] === "no" && <>{field("repeatedFindings","Repeated findings for 18b",{multiline:true})}{field("repeatedAction","Action taken for repeated findings",{multiline:true})}</>}{["18b","19","20"].includes(q.id) && findings(data).some(f => f.id === q.id) && actionFields(q)}</section>)}</div></>;
  return null;
}
