import DeleteDraftButton from '../monitoring/DeleteDraftButton';
import ReviewUpload from '../monitoring/ReviewUpload';
import { usePageNavigation } from '../navigation/PageNavigation';
import PdfUploadPicker from '../monitoring/PdfUploadPicker';
import React, { useEffect, useState } from "react";
import RestartMonitoringButton from "../monitoring/RestartMonitoringButton";
import { MONITORING_TYPES, recordLabel, typeLabel, hasCurrentPdf, sameAssignment } from "../monitoring/types";
import PdfReviewWorkspace from "./PdfReviewWorkspace";
import { localDate, schoolYear } from "./model";
import { SLOTS, STATUSES, canDeleteDraft, canEdit, canRestart, editableGuided, slotProgress } from "./workflow";
import { getMonitoring, deleteDraft, restartMonitoring, createMonitoringSite, submitReviewedUpload, reviewAction, downloadReport } from "./service";

export default function MonitoringHome({ token, records, context, location, onOpen, onStart, onRefresh, onReviewActive, initialType="supper" }) {
  const supervisor=context?.actor_role === "supervisor";
  const sites=context?.monitoring_sites || [{id:"",name:"Main Site",kind:"main"}];
  const [siteId,setSiteId]=useState(sites[0]?.id || "");
  const [monitoringType,setMonitoringType]=useState(initialType);
  const [addingSite,setAddingSite]=useState(false);
  const [siteName,setSiteName]=useState("");
  const [siteKind,setSiteKind]=useState("offsite");
  const identity={monitoringType,monitoringSiteId:siteId};
  const [year,setYear]=useState(schoolYear(localDate()));
  const [selected,setSelected]=useState(null);
  const [reviewing,setReviewing]=useState(null);
  useEffect(()=>{onReviewActive?.(!!reviewing);return()=>onReviewActive?.(false);},[reviewing,onReviewActive]);
  const [upload,setUpload]=useState(false);
  const [reviewUpload,setReviewUpload]=useState(false);
  const [metadata,setMetadata]=useState({});
  const [files,setFiles]=useState([]);
  const [comment,setComment]=useState("");
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  usePageNavigation({ active: !!(selected || upload), level: 2, title: upload ? 'Upload Existing Monitoring' : selected ? recordLabel(selected) : 'Monitoring', destination: supervisor ? 'Monitoring' : 'Monitorings', disabled: busy, onNavigate: () => { if (upload && files.length && !window.confirm('Discard this unsubmitted upload?')) return; setSelected(null);setUpload(false);setReviewUpload(false);setFiles([]);setError(''); } });
  const role=selected?.monitor_role || context?.actor_role || "manager";
  const slots=Object.keys(SLOTS).filter(s=>role === "supervisor" ? s === "supervisor" : s !== "supervisor");
  const occupied=s=>metadata.monitoringType==="supper" && records.some(r=>r.id!==selected?.id && r.school_year===metadata.schoolYear && sameAssignment(r,metadata.monitoringSiteId,metadata.monitoringType) && r.monitoring_slot===s && r.status!=="deleted");
  const freeSlot=Object.keys(SLOTS).find(s=>(supervisor ? s==='supervisor' : s!=='supervisor') && !records.some(r=>r.school_year===year && sameAssignment(r,siteId,monitoringType) && r.monitoring_slot===s && r.status!=='deleted'));
  const displaySite = (id, fallback='Main Site') => {
    const site=sites.find(item=>item.id===id);
    return (site?.kind==='main' || (!site && fallback==='Main Site')) ? (location.school_name || site?.name || fallback) : (site?.name || fallback);
  };
  const managerLabel = record => recordLabel({...record,monitoring_site_name:displaySite(record.monitoring_site_id,record.monitoring_site_name)});
  const label = record => supervisor ? recordLabel(record) : managerLabel(record);
  const years=[...new Set([year,...records.map(r=>r.school_year),...Array.from({length:6},(_,i)=>{const start=Number(schoolYear(localDate()).slice(0,4))-i;return `${start}-${String(start+1).slice(-2)}`;})])].filter(Boolean).sort().reverse();
  async function run(fn) { setBusy(true);setError("");try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);} }
  function beginUpload(record=null) {
    setSelected(record);setFiles([]);setReviewUpload(false);setUpload(true);
    setMetadata({monitoringType:record?.monitoring_type || monitoringType,monitoringSiteId:record?.monitoring_site_id || siteId,monitoringNumber:record?.monitoring_number || "",monitoringDate:record?.monitoring_date || "",schoolYear:record?.school_year || year,monitoringSlot:record?.monitoring_slot || freeSlot || "manager_1",monitorName:record?.payload?.monitorName || record?.created_by_name || context.monitor_name});
  }
  async function action(name) {
    await run(async()=>{const next=await reviewAction(token,selected,name,comment);setSelected(next || null);await onRefresh();});
  }
  async function open(item) {
    await run(async()=>{const loaded=await getMonitoring(token,item.id);setComment("");
      if (!supervisor && loaded.source!=='uploaded' && editableGuided(loaded,context)) onOpen(loaded);
      else setSelected(loaded);
    });
  }
  function list(title,rows) {
    if(!supervisor && ['Corrections Requested','Completed / Accepted'].includes(title)) return <section className="sm-card sm-compact-section"><h2>{title}</h2>{rows.length===0 ? <p>No monitorings in this group.</p> : <ul className="sm-compact-records">{rows.map(r=><li key={r.id}><strong>{label(r)}</strong><span>{r.monitoring_date || 'Date pending'}</span><span className="sm-compact-comment">{title==='Corrections Requested' ? (r.review_comments ? `Supervisor: ${r.review_comments}` : 'Review the requested corrections.') : STATUSES[r.status]}</span><button type="button" disabled={busy} onClick={()=>open(r)}>View</button></li>)}</ul>}</section>;
    return <section className="sm-card"><h2>{title}</h2>{rows.length===0 ? <p>No monitorings in this group.</p> : <ul className="sm-records">{rows.map(r=><li key={r.id}><div><strong>{label(r)} · {r.monitoring_date || "Date pending"}</strong><span>{r.school_year} · {STATUSES[r.status]}</span><span>{r.monitor_role==='supervisor' ? 'Supervisor / AFSS' : 'Manager'} · {r.source==='uploaded' ? 'Uploaded PDF' : 'Created in SPARK'}</span><span>Monitor: {r.payload?.monitorName || r.created_by_name || r.monitor_name}</span>{r.review_comments && <p className="sm-notice">Supervisor: {r.review_comments}</p>}</div><button type="button" disabled={busy} onClick={()=>open(r)}>{!supervisor && r.source!=='uploaded' && editableGuided(r,context) ? 'Resume' : 'View'}</button>{canDeleteDraft(r,context) && <DeleteDraftButton disabled={busy} onDelete={()=>run(async()=>{await deleteDraft(token,r);await onRefresh();})}/>}{hasCurrentPdf(r) && <button type="button" disabled={busy} onClick={()=>run(async()=>setReviewing(await getMonitoring(token,r.id)))}>{supervisor?'Review PDF':'View PDF & Supervisor Markup'}</button>}</li>)}</ul>}</section>; }
  const active=records.filter(r=>r.school_year===year && r.status!=='deleted' && (supervisor || sameAssignment(r,siteId,monitoringType)));
  if(reviewing) return <PdfReviewWorkspace token={token} initialRecord={reviewing} school={location} supervisor={supervisor} backLabel={selected ? 'Monitoring Details' : undefined} onBack={result=>run(async()=>{if(result?.deleted)setSelected(null);else if(selected)setSelected(await getMonitoring(token,selected.id));setReviewing(null);await onRefresh();})}/>;
  if(upload && reviewUpload) return <ReviewUpload token={token} metadata={metadata} school={location} siteName={sites.find(s=>s.id===metadata.monitoringSiteId)?.name || "Main Site"} files={files} onFiles={setFiles} busy={busy} error={error} onBack={()=>{setReviewUpload(false);setError("");}} onSubmit={bytes=>run(async()=>{
    let saved=await submitReviewedUpload(token,selected,metadata,bytes);
    // Keep a saved correction recoverable if the separate resubmit request fails.
    setSelected(saved);setUpload(false);setReviewUpload(false);setFiles([]);
    if(saved.status==='corrections_requested') {saved=await reviewAction(token,saved,'resubmit','');setSelected(saved);}
    await onRefresh();
  })}/>;
  if(upload) return <section className="sm-card"><h2>{selected ? 'Replace PDF' : 'Upload Existing Monitoring'}</h2><p>{typeLabel(metadata.monitoringType)} · {sites.find(s=>s.id===metadata.monitoringSiteId)?.name || "Main Site"}</p><p>{location.school_name} · PDFs up to 2 MB, 1–20 pages. The Supervisor reviews the document manually.</p>{error && <p role="alert" className="sm-error">{error}</p>}<fieldset disabled={busy} className="sm-editor"><label>Monitoring date<input type="date" value={metadata.monitoringDate} onChange={e=>setMetadata({...metadata,monitoringDate:e.target.value,schoolYear:schoolYear(e.target.value)||metadata.schoolYear})}/></label><label>School year<input value={metadata.schoolYear} placeholder="2026-27" onChange={e=>setMetadata({...metadata,schoolYear:e.target.value})}/></label>{metadata.monitoringType==="supper" ? <label>Monitoring slot<select value={metadata.monitoringSlot} onChange={e=>setMetadata({...metadata,monitoringSlot:e.target.value})}>{slots.map(s=><option key={s} value={s} disabled={occupied(s)}>{SLOTS[s]}{occupied(s)?' — already exists':''}</option>)}</select></label> : <label>Monitoring number<input type="number" min="1" step="1" value={metadata.monitoringNumber} onChange={e=>setMetadata({...metadata,monitoringNumber:e.target.value})}/></label>}<label>Monitor / manager<input value={metadata.monitorName} onChange={e=>setMetadata({...metadata,monitorName:e.target.value})}/></label><PdfUploadPicker files={files} onChange={setFiles} disabled={busy}/><div className="sm-actions"><button type="button" onClick={()=>{setUpload(false);setFiles([]);}}>Cancel</button><button type="button" className="sm-primary" disabled={!files.length || !metadata.monitoringDate || !metadata.monitorName?.trim() || (metadata.monitoringType!=="supper" && !/^[1-9][0-9]*$/.test(metadata.monitoringNumber)) || occupied(metadata.monitoringSlot)} onClick={()=>{setError("");setReviewUpload(true);}}>Review Upload</button></div></fieldset></section>;
  if(selected) return <section className="sm-card"><h2>{label(selected)}</h2><p>{location.school_name} · {selected.school_year} · {selected.monitoring_date}</p><p>{selected.payload?.monitorName || selected.created_by_name} · {selected.monitor_role==='supervisor'?'Supervisor / AFSS':'Manager'}</p><p><strong>{STATUSES[selected.status]}</strong> · {selected.source==='uploaded'?'Uploaded PDF':'Created in SPARK'}</p>{!supervisor && selected.source==='uploaded' && selected.status==='corrections_requested' && canEdit(selected,context) && <p>Upload one or two corrected PDFs, review the combined document, then submit it again for Supervisor review.</p>}{selected.review_comments && <div className="sm-notice"><strong>Supervisor comments</strong><p>{selected.review_comments}</p></div>}{error && <p role="alert" className="sm-error">{error}</p>}<div className="sm-actions"><button type="button" disabled={busy} onClick={()=>{setSelected(null);setError('');}}>Back to History</button>{hasCurrentPdf(selected) && <button type="button" disabled={busy} onClick={()=>setReviewing(selected)}>{supervisor?"Review PDF":"View PDF & Supervisor Markup"}</button>}{hasCurrentPdf(selected) && <button type="button" disabled={busy} onClick={()=>run(()=>downloadReport(token,selected))}>View / Download PDF</button>}{canRestart(selected,context) && <RestartMonitoringButton disabled={busy} onRestart={()=>run(async()=>{const fresh=await restartMonitoring(token,selected);setSelected(null);await onRefresh();onOpen(fresh);})}/>} {selected.source!=='uploaded' && <button type="button" disabled={busy} onClick={()=>onOpen(selected)}>{editableGuided(selected,context) ? 'Resume Guided Monitoring' : 'View Guided Monitoring'}</button>}{canEdit(selected,context) && (supervisor || selected.source==='uploaded') && <button type="button" disabled={busy} onClick={()=>beginUpload(selected)}>{selected.status==='corrections_requested' ? 'Upload Corrected PDF' : 'Replace PDF'}</button>}</div>{supervisor && selected.status!=='deleted' && <fieldset className="sm-editor" disabled={busy}><label>Supervisor review comments<textarea rows={4} maxLength={4000} value={comment} onChange={e=>setComment(e.target.value)}/></label><div className="sm-actions"><button type="button" disabled={selected.locked || !comment.trim()} onClick={()=>action('comment')}>Save Comment</button>{selected.status==='submitted' && <><button type="button" disabled={!comment.trim()} onClick={()=>action('return')}>Return for Correction</button><button type="button" onClick={()=>action('accept')}>Accept Monitoring</button></>}{selected.locked && <button type="button" disabled={!comment.trim()} onClick={()=>action('unlock')}>Unlock for Correction</button>}<button type="button" onClick={()=>{if(window.confirm('Delete this monitoring and its PDF? This cannot be undone.')) action('delete');}}>Delete Monitoring</button></div></fieldset>}</section>;
  return <>{error && <p role="alert" className="sm-error">{error}</p>}<section className="sm-card"><h2>School-year Progress</h2><div className="sm-grid"><label>Monitoring type<select aria-label="Monitoring type" value={monitoringType} onChange={e=>setMonitoringType(e.target.value)}>{Object.entries(MONITORING_TYPES).map(([type,config])=><option key={type} value={type} >{config.label}{config.enabled ? "" : " — Guided workflow coming later"}</option>)}</select></label><label>Monitored site / program<select aria-label="Monitored site / program" value={siteId} onChange={e=>setSiteId(e.target.value)}>{sites.map(site=><option key={site.id} value={site.id}>{site.name}{site.kind==='main'?'':` (${site.kind === 'eec' ? 'EEC' : site.kind})`}</option>)}</select></label></div>{supervisor && <><button type="button" disabled={busy} onClick={()=>setAddingSite(!addingSite)}>Add Site / Program</button>{addingSite && <div className="sm-subcard"><label>Site / program name<input maxLength={120} value={siteName} onChange={e=>setSiteName(e.target.value)}/></label><label>Site kind<select aria-label="Site kind" value={siteKind} onChange={e=>setSiteKind(e.target.value)}><option value="offsite">Offsite</option><option value="eec">EEC</option><option value="program">Program</option></select></label><button type="button" disabled={busy||!siteName.trim()} onClick={()=>run(async()=>{const site=await createMonitoringSite(token,siteName,siteKind);await onRefresh();setSiteId(site.id);setSiteName('');setAddingSite(false);})}>Save Site / Program</button><button type="button" onClick={()=>setAddingSite(false)}>Cancel</button></div>}</>}<label>School year{supervisor ? <input value={year} onChange={e=>setYear(e.target.value)} placeholder="2026-27"/> : <select aria-label="School year" value={year} onChange={e=>setYear(e.target.value)}>{years.map(value=><option key={value} value={value}>{value}</option>)}</select>}</label>{!supervisor && <p><strong>Select a monitoring below to get started.</strong>{context?.allow_manager_uploads ? ' If you already completed your monitoring outside of SPARK, select Upload Existing Monitoring.' : ''}</p>}<div className="sm-slot-grid">{slotProgress(records,year,siteId,monitoringType).map(p=>{
      const title=monitoringType==='supper' ? `${p.label.split(' · ')[0]} - ${supervisor ? (sites.find(s=>s.id===siteId)?.name || 'Main Site') : displaySite(siteId)}` : p.label;
      const performer=monitoringType==='supper' ? p.label.split(' · ')[1] : p.record?.monitor_role==='supervisor'?'Supervisor / AFSS':'Manager';
      const status=p.record ? STATUSES[p.record.status] : 'Not Started';
      if(supervisor)return <div key={p.slot}><strong>{title}</strong><p>{performer}</p><p>{status}</p></div>;
      const canStart=monitoringType==='supper' && p.slot!=='supervisor';
      const tone=['accepted','completed'].includes(p.record?.status)?'done':p.record?.status==='submitted'?'pending':'incomplete';
      return <button key={p.slot} type="button" className={`sm-status-card sm-status-${tone}`} disabled={busy || (!p.record && !canStart)} onClick={()=>p.record ? open(p.record) : onStart(year,p.slot,identity)}><strong>{title}</strong><span>{performer}</span><span>{status}</span>{!p.record && !canStart && <small>Started by Supervisor / AFSS</small>}</button>;
    })}</div><div className="sm-actions">{(supervisor || monitoringType!=="supper") && <button type="button" className="sm-primary" disabled={busy || !freeSlot || !MONITORING_TYPES[monitoringType].enabled} onClick={()=>onStart(year,freeSlot,identity)}>{supervisor ? '+ Start Supervisor Monitoring' : '+ Start New Monitoring'}</button>}{!supervisor && context?.allow_manager_uploads && <button type="button" disabled={busy || (monitoringType==="supper" && !freeSlot)} onClick={()=>beginUpload()}>Upload Existing Monitoring</button>}<button type="button" disabled={busy} onClick={()=>run(onRefresh)}>Refresh</button></div>{monitoringType==="supper" && !freeSlot && <p>All slots for your role at this site and monitoring type have records. Resume a draft or ask the Supervisor to resolve a slot.</p>}</section>{list('Drafts / In Progress',active.filter(r=>r.status==='draft'))}{list('Submitted for Review',active.filter(r=>r.status==='submitted'))}{list('Corrections Requested',active.filter(r=>r.status==='corrections_requested'))}{list('Completed / Accepted',active.filter(r=>['accepted','completed'].includes(r.status)))}{supervisor && list('Previous Monitorings',records.filter(r=>r.school_year!==year && ['accepted','completed'].includes(r.status)))}</>;
}
