import React, { useEffect, useState } from "react";
import SupperMonitoringPage from "./SupperMonitoringPage";
import { supervisorOverview, setUploads } from "./service";
import { SLOTS, STATUSES, slotProgress } from "./workflow";
import { schoolYear, localDate } from "./model";
import "./supperMonitoring.css";
export default function SupervisorSupperMonitoringPage({ supervisorPin, onBack }) {
  const [overview,setOverview]=useState({schools:[],records:[]});const [school,setSchool]=useState(null);
  const [year,setYear]=useState(schoolYear(localDate()));const [schoolFilter,setSchoolFilter]=useState('');const [status,setStatus]=useState('');const [role,setRole]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function load(){setBusy(true);setError('');try{setOverview(await supervisorOverview(supervisorPin));}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{load();},[supervisorPin]);
  if(school) return <SupperMonitoringPage key={school.id} location={school} employee={{employee_name:'Supervisor / AFSS'}} supervisorPin={supervisorPin} onBack={()=>{setSchool(null);load();}}/>;
  const rows=overview.schools.filter(s=>(!schoolFilter || String(s.id)===schoolFilter)).map(s=>({...s,slots:slotProgress(overview.records.filter(r=>r.location_id===s.id),year)})).filter(s=>s.slots.some(p=>(!role || (p.slot==='supervisor'?'supervisor':'manager')===role) && (!status || (p.record?.status || 'not_started')===status)));
  return <div className="login-app sm-app"><main className="sm-main"><button type="button" onClick={onBack}>← Command Center</button><h1>Supervisor Supper Monitoring</h1>{error && <p role="alert" className="sm-error">{error}</p>}<section className="sm-card"><label className="sm-check"><input type="checkbox" checked={!!overview.allow_manager_uploads} disabled={busy} onChange={async e=>{setBusy(true);try{await setUploads(supervisorPin,e.target.checked);await load();}catch(err){setError(err.message);}finally{setBusy(false);}}}/>Allow Manager PDF Uploads</label><p>Turning this off prevents new manager uploads. Existing PDFs and corrections remain available.</p><div className="sm-grid"><label>School<select value={schoolFilter} onChange={e=>setSchoolFilter(e.target.value)}><option value="">All authorized schools</option>{overview.schools.map(s=><option key={s.id} value={s.id}>{s.school_name}</option>)}</select></label><label>School year<input value={year} onChange={e=>setYear(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="not_started">Not Started</option>{Object.entries(STATUSES).filter(([k])=>k!=='deleted').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Performed by<select value={role} onChange={e=>setRole(e.target.value)}><option value="">Manager and Supervisor</option><option value="manager">Manager</option><option value="supervisor">Supervisor / AFSS</option></select></label></div><button type="button" disabled={busy} onClick={load}>Refresh Overview</button><p>Choose a school below to review its history or start your Supervisor monitoring.</p></section>{rows.map(s=><section key={s.id} className="sm-card"><h2>{s.school_name}</h2><div className="sm-slot-grid">{s.slots.map(p=><div key={p.slot}><strong>{SLOTS[p.slot]}</strong><p>{p.record ? STATUSES[p.record.status] : 'Not Started'}</p></div>)}</div><button type="button" onClick={()=>setSchool(s)}>Open School Monitorings</button></section>)}{!busy && !rows.length && <p>No schools match these filters.</p>}</main></div>;
}
