BEGIN;
CREATE FUNCTION pg_temp.check_it(ok boolean,label text) RETURNS void LANGUAGE plpgsql AS $$BEGIN IF ok IS NOT TRUE THEN RAISE EXCEPTION 'FAIL: %',label; END IF;END$$;
DO $$
DECLARE admin text; manager text; base jsonb; c jsonb; feedback_id uuid; entry uuid; monitoring uuid; site uuid; claimed jsonb; subid uuid;
BEGIN
 admin:=public.spark_login(p_role=>'supervisor',p_pin=>'1618');
 manager:=public.spark_login(p_role=>'employee',p_employee_id=>900001,p_pin=>'3141');
 PERFORM pg_temp.check_it(manager IS NOT NULL,'manager fixture logged in');
 BEGIN PERFORM public.supervisor_notification_preview_counts(manager); RAISE EXCEPTION 'Manager saw preview counts'; EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE '%Supervisor authorization%' THEN RAISE; END IF; END;
 c:=public.supervisor_notification_preview_counts(admin);
 INSERT INTO october_dev.entries(location_id,quest,photo_path,consent) VALUES(900001,992,'synthetic-preview.webp',true);
 PERFORM pg_temp.check_it((public.supervisor_notification_preview_counts(admin)->>'quests')::int=(c->>'quests')::int+1,'isolated preview counts use development Games');
 PERFORM set_config('test.supervisor',admin,true);
 base:=public.supervisor_notification_counts(admin);
 BEGIN PERFORM public.supervisor_notification_counts(manager); RAISE EXCEPTION 'Manager saw counts'; EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE '%Supervisor authorization%' THEN RAISE; END IF; END;
 BEGIN PERFORM public.supervisor_notification_counts('fake'); RAISE EXCEPTION 'Anonymous saw counts'; EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE '%Supervisor authorization%' THEN RAISE; END IF; END;
 INSERT INTO public.spark_feedback(category,message,page_route) VALUES('Bug','Synthetic notification test','test') RETURNING spark_feedback.id INTO feedback_id;
 c:=public.supervisor_notification_counts(admin);
 PERFORM pg_temp.check_it((c->>'feedback')::int=(base->>'feedback')::int+1,'new feedback increases count');
 PERFORM public.mark_spark_feedback_read(admin,feedback_id,true);
 PERFORM pg_temp.check_it(public.supervisor_notification_counts(admin)->>'feedback'=base->>'feedback','read decreases');
 PERFORM public.mark_spark_feedback_read(admin,feedback_id,false);
 PERFORM pg_temp.check_it(EXISTS(SELECT 1 FROM public.list_spark_feedback(admin,'Unread') f WHERE f.id=feedback_id),'unread review includes feedback');
 PERFORM public.update_spark_feedback_status(admin,feedback_id,'Resolved');
 PERFORM pg_temp.check_it(public.supervisor_notification_counts(admin)->>'feedback'=base->>'feedback','resolve marks read atomically');
 INSERT INTO october_live.entries(location_id,quest,photo_path,consent) VALUES(900001,991,'synthetic.webp',true) RETURNING entries.id INTO entry;
 PERFORM pg_temp.check_it((public.supervisor_notification_counts(admin)->>'quests')::int=(base->>'quests')::int+1,'quest submission increases');
 UPDATE october_live.entries SET state='approved' WHERE entries.id=entry;
 PERFORM pg_temp.check_it(public.supervisor_notification_counts(admin)->>'quests'=base->>'quests','approval decreases');
 UPDATE october_live.entries SET state='pending' WHERE entries.id=entry;
 UPDATE october_live.entries SET state='rejected' WHERE entries.id=entry;
 PERFORM pg_temp.check_it(public.supervisor_notification_counts(admin)->>'quests'=base->>'quests','rejection decreases');
 INSERT INTO october_live.entries(location_id,quest,photo_path,consent) VALUES(900001,0,'synthetic-door.webp',true);
 PERFORM pg_temp.check_it(public.supervisor_notification_counts(admin)->>'quests'=base->>'quests','door entries excluded from side quest category');
 SELECT ms.id INTO site FROM public.monitoring_sites ms WHERE location_id=900001 LIMIT 1;
 INSERT INTO public.monitoring_records(location_id,created_by_name,monitoring_site_id,monitoring_type,status)
 VALUES(900001,'Synthetic',site,'breakfast','draft') RETURNING monitoring_records.id INTO monitoring;
 UPDATE public.monitoring_records SET status='submitted' WHERE monitoring_records.id=monitoring;
 PERFORM pg_temp.check_it((public.supervisor_notification_counts(admin)->>'monitoring')::int=(base->>'monitoring')::int+1,'monitoring submitted increases');
 UPDATE public.monitoring_records SET status='corrections_requested' WHERE monitoring_records.id=monitoring;
 PERFORM pg_temp.check_it(public.supervisor_notification_counts(admin)->>'monitoring'=base->>'monitoring','returned decreases');
 UPDATE public.monitoring_records SET status='submitted' WHERE monitoring_records.id=monitoring;
 UPDATE public.monitoring_records SET status='accepted',locked=true WHERE monitoring_records.id=monitoring;
 PERFORM pg_temp.check_it(public.supervisor_notification_counts(admin)->>'monitoring'=base->>'monitoring','accepted decreases');
 PERFORM public.supervisor_push_service('subscribe',jsonb_build_object('pin',admin,'device_hash','synthetic-device','subscription','{"endpoint":"https://web.push.apple.com/synthetic"}'::jsonb));
 PERFORM pg_temp.check_it(jsonb_array_length(public.supervisor_push_service('claim')->'subscriptions')=0,'registration does not spam existing backlog');
 PERFORM public.mark_spark_feedback_read(admin,feedback_id,false);
 claimed:=public.supervisor_push_service('claim');
 PERFORM pg_temp.check_it(jsonb_array_length(claimed->'subscriptions')=1,'changes queued');
 PERFORM pg_temp.check_it(jsonb_array_length(public.supervisor_push_service('claim')->'subscriptions')=0,'concurrent worker cannot claim leased subscription');
 subid:=(claimed->'subscriptions'->0->>'id')::uuid;
 PERFORM public.supervisor_push_service('ack',jsonb_build_object('id',subid,'lease',claimed->>'lease','version',claimed->'counts'->>'version','status','sent'));
 PERFORM pg_temp.check_it(jsonb_array_length(public.supervisor_push_service('claim')->'subscriptions')=0,'sent version not delivered twice');
 PERFORM public.mark_spark_feedback_read(admin,feedback_id,true);
 claimed:=public.supervisor_push_service('claim');
 PERFORM pg_temp.check_it(jsonb_array_length(claimed->'subscriptions')=1,'decreases queued too');
 PERFORM public.supervisor_push_service('ack',jsonb_build_object('id',subid,'lease',claimed->>'lease','status','retry'));
 PERFORM pg_temp.check_it(jsonb_array_length(public.supervisor_push_service('claim')->'subscriptions')=0,'failed endpoints back off');
 PERFORM public.supervisor_push_service('unsubscribe','{"device_hash":"synthetic-device"}');
 PERFORM pg_temp.check_it(NOT EXISTS(SELECT 1 FROM spark_private.push_subscriptions WHERE id=subid),'signout removes subscription');
END $$;
SET LOCAL ROLE anon;
DO $$BEGIN
 PERFORM pg_temp.check_it((public.supervisor_notification_counts(current_setting('test.supervisor'))->>'total')::int>=0,'valid supervisor RPC accessible');
 BEGIN PERFORM public.supervisor_push_service('config'); RAISE EXCEPTION 'Secret service exposed'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN PERFORM * FROM spark_private.push_subscriptions; RAISE EXCEPTION 'Subscriptions exposed'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN PERFORM public.mark_spark_feedback_read('fake',gen_random_uuid(),true); RAISE EXCEPTION 'Unauthenticated marking'; EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE '%Supervisor authorization%' THEN RAISE; END IF; END;
END $$;
ROLLBACK;
SELECT 'PASS: counts, feedback read/unread, approval/return transitions, role isolation, deduplication, leases, backoff, and unsubscribe. All synthetic writes rolled back.';

