-- Daily Bites school-level game progress and atomic completion rewards.
-- Run this migration in the Supabase SQL editor before enabling the games.

create table if not exists public.daily_bites_game_progress (
  id bigint generated by default as identity primary key,
  location_id bigint not null,
  employee_id bigint null,
  employee_name text null,
  game_type text not null check (game_type in ('word', 'spark_sort')),
  puzzle_id text not null,
  service_date date not null,
  status text not null default 'in_progress' check (status in ('in_progress', 'won', 'lost')),
  state jsonb not null default '{}'::jsonb,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz null,
  updated_at timestamptz not null default now(),
  unique (location_id, game_type, puzzle_id)
);

create index if not exists daily_bites_game_progress_location_date_idx
  on public.daily_bites_game_progress (location_id, service_date desc);

alter table public.daily_bites_game_progress enable row level security;

grant select, insert, update on table public.daily_bites_game_progress
  to anon, authenticated;
grant usage, select on sequence public.daily_bites_game_progress_id_seq
  to anon, authenticated;

drop policy if exists "Daily Bites progress is readable" on public.daily_bites_game_progress;
create policy "Daily Bites progress is readable"
  on public.daily_bites_game_progress for select
  to anon, authenticated
  using (true);

drop policy if exists "Daily Bites progress can be created" on public.daily_bites_game_progress;
create policy "Daily Bites progress can be created"
  on public.daily_bites_game_progress for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Daily Bites progress can be updated" on public.daily_bites_game_progress;
create policy "Daily Bites progress can be updated"
  on public.daily_bites_game_progress for update
  to anon, authenticated
  using (true)
  with check (true);

create or replace function public.complete_daily_bites_game(
  p_location_id bigint,
  p_employee_id bigint,
  p_employee_name text,
  p_game_type text,
  p_puzzle_id text,
  p_service_date date,
  p_state jsonb,
  p_attempt_count integer,
  p_points integer,
  p_point_type text,
  p_description text,
  p_unique_key text
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
begin
  if p_game_type not in ('word', 'spark_sort') then
    raise exception 'Unsupported Daily Bites game type';
  end if;

  if p_points < 0 or p_points > 5 then
    raise exception 'Daily Bites game points must be between 0 and 5';
  end if;

  insert into public.daily_bites_game_progress (
    location_id, employee_id, employee_name, game_type, puzzle_id,
    service_date, status, state, attempt_count, completed_at, updated_at
  ) values (
    p_location_id, p_employee_id, p_employee_name, p_game_type, p_puzzle_id,
    p_service_date, 'won', coalesce(p_state, '{}'::jsonb), p_attempt_count, now(), now()
  )
  on conflict (location_id, game_type, puzzle_id) do update set
    employee_id = excluded.employee_id,
    employee_name = excluded.employee_name,
    status = 'won',
    state = excluded.state,
    attempt_count = excluded.attempt_count,
    completed_at = coalesce(public.daily_bites_game_progress.completed_at, now()),
    updated_at = now();

  if p_points > 0 then
    insert into public.spark_points (
      location_id, points, point_type, description, service_date, source,
      employee_id, employee_name, unique_key
    ) values (
      p_location_id, p_points, p_point_type, p_description, p_service_date,
      'automatic', p_employee_id, p_employee_name, p_unique_key
    )
    on conflict (unique_key) do nothing;
  end if;

  return true;
end;
$$;

grant execute on function public.complete_daily_bites_game(
  bigint, bigint, text, text, text, date, jsonb, integer, integer, text, text, text
) to anon, authenticated;
