create table if not exists public.ar_training_question_keys (
  question_id text primary key,
  correct_index integer not null check (correct_index between 0 and 3),
  approved_source_chunk_id text not null,
  active boolean not null default true
);

create table if not exists public.ar_training_daily_progress (
  location_id bigint not null,
  service_date date not null,
  points_awarded integer not null default 0 check (points_awarded between 0 and 10),
  correct_answers integer not null default 0,
  total_attempts integer not null default 0,
  awarded_question_ids jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (location_id, service_date)
);

create table if not exists public.ar_training_attempts (
  id bigint generated by default as identity primary key,
  location_id bigint not null,
  employee_id bigint null,
  employee_name text null,
  service_date date not null,
  question_id text not null references public.ar_training_question_keys(question_id),
  selected_index integer not null check (selected_index between 0 and 3),
  is_correct boolean not null,
  points_awarded integer not null default 0 check (points_awarded in (0, 2)),
  answered_at timestamptz not null default now()
);

create index if not exists ar_training_attempts_location_date_idx
  on public.ar_training_attempts (location_id, service_date desc);

alter table public.ar_training_question_keys enable row level security;
alter table public.ar_training_daily_progress enable row level security;
alter table public.ar_training_attempts enable row level security;

revoke all on public.ar_training_question_keys from anon, authenticated;
grant select on public.ar_training_daily_progress to anon, authenticated;
revoke insert, update, delete on public.ar_training_daily_progress from anon, authenticated;
revoke all on public.ar_training_attempts from anon, authenticated;

drop policy if exists "AR progress is readable" on public.ar_training_daily_progress;
create policy "AR progress is readable"
  on public.ar_training_daily_progress for select
  to anon, authenticated
  using (true);

insert into public.ar_training_question_keys (question_id, correct_index, approved_source_chunk_id) values
  ('ar-eec-production-daily', 1, 'ASKP1-C000036'),
  ('ar-eec-temp-timing', 2, 'ASKP1-C000036'),
  ('ar-eec-record-retention', 2, 'ASKP1-C000040'),
  ('ar-eec-leftovers-scenario', 2, 'ASKP1-C000040'),
  ('ar-special-diet-first-step', 1, 'ASKP1-C000052'),
  ('ar-civil-rights-poster', 1, 'ASKP1-C000055'),
  ('ar-manual-count-backup', 1, 'ASKP1-C000168'),
  ('ar-production-balance-point', 0, 'ASKP1-C000168'),
  ('ar-dropped-meal-claim', 2, 'ASKP1-C000168'),
  ('ar-edit-check-comment', 0, 'ASKP1-C000171'),
  ('ar-central-event-records', 1, 'ASKP1-C000172'),
  ('ar-field-trip-request-lead', 3, 'ASKP1-C000299'),
  ('ar-field-trip-pos', 0, 'ASKP1-C000300'),
  ('ar-field-trip-four-hours', 1, 'ASKP1-C000300'),
  ('ar-field-trip-special-diet', 2, 'ASKP1-C000301')
on conflict (question_id) do update set
  correct_index = excluded.correct_index,
  approved_source_chunk_id = excluded.approved_source_chunk_id,
  active = true;

create or replace function public.submit_ar_training_answer(
  p_location_id bigint,
  p_employee_id bigint,
  p_employee_name text,
  p_service_date date,
  p_question_id text,
  p_selected_index integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_correct_index integer;
  v_is_correct boolean;
  v_progress public.ar_training_daily_progress%rowtype;
  v_points integer := 0;
  v_already_awarded boolean := false;
  v_is_weekday boolean;
begin
  if p_location_id is null or p_service_date is null then
    raise exception 'Location and service date are required';
  end if;
  if p_service_date <> (now() at time zone 'America/Los_Angeles')::date then
    raise exception 'AR Training answers must use today in America/Los_Angeles';
  end if;
  if p_selected_index < 0 or p_selected_index > 3 then
    raise exception 'Invalid answer selection';
  end if;

  select correct_index into v_correct_index
  from public.ar_training_question_keys
  where question_id = p_question_id and active = true;
  if not found then raise exception 'Unknown AR training question'; end if;

  v_is_correct := p_selected_index = v_correct_index;
  v_is_weekday := extract(isodow from p_service_date) between 1 and 5;

  insert into public.ar_training_daily_progress (location_id, service_date)
  values (p_location_id, p_service_date)
  on conflict (location_id, service_date) do nothing;

  select * into v_progress
  from public.ar_training_daily_progress
  where location_id = p_location_id and service_date = p_service_date
  for update;

  v_already_awarded := v_progress.awarded_question_ids ? p_question_id;
  if v_is_correct and v_is_weekday and not v_already_awarded and v_progress.points_awarded < 10 then
    v_points := least(2, 10 - v_progress.points_awarded);
  end if;

  update public.ar_training_daily_progress set
    points_awarded = points_awarded + v_points,
    correct_answers = correct_answers + case when v_is_correct then 1 else 0 end,
    total_attempts = total_attempts + 1,
    awarded_question_ids = case when v_points > 0
      then awarded_question_ids || to_jsonb(p_question_id)
      else awarded_question_ids end,
    updated_at = now()
  where location_id = p_location_id and service_date = p_service_date
  returning * into v_progress;

  insert into public.ar_training_attempts (
    location_id, employee_id, employee_name, service_date,
    question_id, selected_index, is_correct, points_awarded
  ) values (
    p_location_id, p_employee_id, p_employee_name, p_service_date,
    p_question_id, p_selected_index, v_is_correct, v_points
  );

  if v_points > 0 then
    insert into public.spark_points (
      location_id, points, point_type, description, service_date, source,
      employee_id, employee_name, unique_key
    ) values (
      p_location_id, v_points, 'ar_training', 'AR Training correct answer',
      p_service_date, 'automatic', p_employee_id, p_employee_name,
      format('ar-training-%s-%s-%s', p_location_id, p_service_date, p_question_id)
    ) on conflict (unique_key) do nothing;
  end if;

  return jsonb_build_object(
    'correct', v_is_correct,
    'points_earned', v_points,
    'daily_points', v_progress.points_awarded,
    'cap_reached', v_progress.points_awarded >= 10,
    'already_awarded', v_already_awarded,
    'weekday', v_is_weekday
  );
end;
$$;

revoke all on function public.submit_ar_training_answer(bigint, bigint, text, date, text, integer) from public;
grant execute on function public.submit_ar_training_answer(bigint, bigint, text, date, text, integer) to anon, authenticated;
