begin;

create table if not exists public.staffing_positions (
  id bigint generated by default as identity primary key,
  school_year text not null,
  source_site_id text not null,
  location_id bigint not null references public.locations(id),
  pwi_position_id text not null,
  employee_name text,
  employee_number text,
  classification_title text not null,
  classification_key text not null check (
    classification_key in (
      'worker','senior_worker','manager_i','manager_ii','manager_iii',
      'manager_iv','manager_v','manager_vi','manager_vii'
    )
  ),
  assigned_daily_hours numeric(6,2) not null check (assigned_daily_hours >= 0),
  assigned_days_per_week numeric(4,2) check (assigned_days_per_week >= 0),
  pwi_pay_level text,
  pwi_job_code text,
  position_filled boolean not null default true,
  active boolean not null default true,
  movable boolean not null default false,
  linked_employee_id bigint references public.employees(id) on delete set null,
  source_as_of date not null,
  updated_at timestamptz not null default now(),
  unique (school_year,pwi_position_id)
);

create unique index if not exists staffing_positions_employee_number_uq
  on public.staffing_positions(school_year,employee_number)
  where employee_number is not null and employee_number <> '00000000' and position_filled;
create index if not exists staffing_positions_location_idx
  on public.staffing_positions(school_year,location_id,active);
create index if not exists staffing_positions_source_site_idx
  on public.staffing_positions(school_year,source_site_id,active);

alter table public.staffing_positions enable row level security;
revoke all on public.staffing_positions from anon,authenticated;

create or replace function public.refresh_monthly_staffing_allocations(
  p_school_year text,
  p_source_site_ids text[] default null
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  delete from public.monthly_staffing_allocations a
  where a.school_year=p_school_year
    and (p_source_site_ids is null or a.source_site_id=any(p_source_site_ids));

  insert into public.monthly_staffing_allocations(
    school_year,source_site_id,classification_key,position_count,filled_count,
    vacant_count,filled_daily_hours,source_as_of
  )
  select school_year,source_site_id,classification_key,
    count(*)::integer,
    count(*) filter (where position_filled)::integer,
    count(*) filter (where not position_filled)::integer,
    coalesce(sum(assigned_daily_hours) filter (where position_filled),0),
    max(source_as_of)
  from public.staffing_positions
  where school_year=p_school_year and active
    and (p_source_site_ids is null or source_site_id=any(p_source_site_ids))
  group by school_year,source_site_id,classification_key;
end $$;

revoke all on function public.refresh_monthly_staffing_allocations(text,text[]) from public;

create or replace function public.get_staff_management_dataset(p_supervisor_pin text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
begin
  if public.verify_supervisor_pin(p_supervisor_pin) is not true then
    raise exception 'Supervisor authorization failed';
  end if;

  return jsonb_build_object(
    'schools',coalesce((
      select jsonb_agg(to_jsonb(s) order by s.school_name)
      from (
        select l.id,l.location_code,l.school_name,
          (select m.source_site_id
           from public.monthly_site_mappings m
           join public.location_information d on d.id=m.main_location_id
           where d.location_code=l.location_code and m.active=true and m.program_type='main'
           order by m.source_site_id limit 1) source_site_id
        from public.locations l
        where l.active=true
          and lower(trim(l.school_name)) not in ('test high school','hawthorne academy')
      ) s
    ),'[]'::jsonb),
    'positions',coalesce((
      select jsonb_agg(to_jsonb(p) order by p.employee_name,p.pwi_position_id)
      from (
        select sp.id,sp.school_year,sp.source_site_id,sp.location_id,
          sp.pwi_position_id,sp.employee_name,sp.employee_number,
          sp.classification_title,sp.classification_key,sp.assigned_daily_hours,
          sp.assigned_days_per_week,sp.pwi_pay_level,sp.position_filled,
          sp.movable,sp.source_as_of,sp.updated_at
        from public.staffing_positions sp
        where sp.active=true and sp.position_filled=true
      ) p
    ),'[]'::jsonb)
  );
end $$;

revoke all on function public.get_staff_management_dataset(text) from public;
grant execute on function public.get_staff_management_dataset(text) to anon,authenticated;

create or replace function public.update_staffing_position(
  p_supervisor_pin text,
  p_position_id bigint,
  p_employee_name text,
  p_employee_number text,
  p_classification_title text,
  p_classification_key text,
  p_assigned_daily_hours numeric,
  p_location_id bigint,
  p_movable boolean
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_old public.staffing_positions%rowtype;
  v_target_source_site_id text;
begin
  if public.verify_supervisor_pin(p_supervisor_pin) is not true then
    raise exception 'Supervisor authorization failed';
  end if;

  select * into v_old from public.staffing_positions where id=p_position_id and active=true for update;
  if not found then raise exception 'Staffing record was not found'; end if;

  if nullif(trim(p_employee_name),'') is null then raise exception 'Employee name is required'; end if;
  if nullif(trim(p_classification_title),'') is null then raise exception 'Classification is required'; end if;
  if p_assigned_daily_hours is null or p_assigned_daily_hours < 0 or p_assigned_daily_hours > 24 then
    raise exception 'Assigned hours must be between 0 and 24';
  end if;
  if p_classification_key not in ('worker','senior_worker','manager_i','manager_ii','manager_iii','manager_iv','manager_v','manager_vi','manager_vii') then
    raise exception 'Classification group is invalid';
  end if;
  if p_location_id<>v_old.location_id and not coalesce(p_movable,false) then
    raise exception 'This fixed position must be explicitly marked movable before reassignment';
  end if;

  select m.source_site_id into v_target_source_site_id
  from public.locations l
  join public.location_information d on d.location_code=l.location_code and d.active=true
  join public.monthly_site_mappings m on m.main_location_id=d.id and m.active=true and m.program_type='main'
  where l.id=p_location_id and l.active=true
    and lower(trim(l.school_name)) not in ('test high school','hawthorne academy')
  order by m.source_site_id limit 1;
  if v_target_source_site_id is null then raise exception 'The target school does not have an active PWI mapping'; end if;

  update public.staffing_positions set
    employee_name=trim(p_employee_name),
    employee_number=nullif(trim(p_employee_number),''),
    classification_title=trim(p_classification_title),
    classification_key=p_classification_key,
    assigned_daily_hours=p_assigned_daily_hours,
    location_id=p_location_id,
    source_site_id=v_target_source_site_id,
    movable=coalesce(p_movable,false),
    updated_at=now()
  where id=p_position_id;

  if v_old.linked_employee_id is not null then
    update public.employees set
      employee_name=trim(p_employee_name),location_id=p_location_id
    where id=v_old.linked_employee_id;
  end if;

  perform public.refresh_monthly_staffing_allocations(
    v_old.school_year,
    array(select distinct x from unnest(array[v_old.source_site_id,v_target_source_site_id]) x)
  );

  return (select to_jsonb(sp) from public.staffing_positions sp where sp.id=p_position_id);
end $$;

revoke all on function public.update_staffing_position(text,bigint,text,text,text,text,numeric,bigint,boolean) from public;
grant execute on function public.update_staffing_position(text,bigint,text,text,text,text,numeric,bigint,boolean) to anon,authenticated;

commit;
