-- Normalize area supervisor data and add maintained coordinates for the shared map.
create table if not exists public.area_supervisors (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text,
  cell_phone text,
  auth_user_id uuid unique,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.area_supervisors enable row level security;
drop policy if exists "area supervisors are readable" on public.area_supervisors;
create policy "area supervisors are readable"
  on public.area_supervisors for select
  to anon, authenticated
  using (active = true);
revoke insert, update, delete on public.area_supervisors from anon, authenticated;
grant select on public.area_supervisors to anon, authenticated;

insert into public.area_supervisors (full_name, email, cell_phone)
select 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'
where not exists (
  select 1 from public.area_supervisors where lower(email) = 'huy.l.nguyen@lausd.net'
);

alter table public.location_information
  add column if not exists supervisor_id bigint references public.area_supervisors(id),
  add column if not exists latitude double precision,
  add column if not exists longitude double precision;

update public.location_information
set supervisor_id = (
  select id from public.area_supervisors
  where lower(email) = 'huy.l.nguyen@lausd.net'
  order by id limit 1
)
where supervisor_id is null;

update public.location_information set site_type = upper(site_type) where site_type is not null;

-- Coordinates are from the City of Los Angeles LAUSD Schools GIS feature layer.
update public.location_information as location
set latitude = coordinates.latitude,
    longitude = coordinates.longitude
from (values
  ('2089', 33.878198307206148, -118.27079967945284),
  ('2527', 33.801505610042845, -118.26277621091823),
  ('4041', 33.882286919040958, -118.28661093769961),
  ('2890', 33.811933259873072, -118.27038257540710),
  ('8529', 33.793606572608709, -118.26201564559645),
  ('4014', 33.788799234071561, -118.26619754797849),
  ('7781', 33.786057698989353, -118.24575741238742),
  ('5753', 33.862937698674443, -118.30592991674318),
  ('7205', 33.857775516667012, -118.26706332084618),
  ('7419', 33.837943512815109, -118.28868905569517),
  ('8487', 33.825658273292802, -118.28492930017507),
  ('2815', 33.822358896578443, -118.28280677557858),
  ('2836', 33.832613520427415, -118.27512189830921),
  ('3452', 33.821577072320636, -118.27188677742384),
  ('8575', 33.822219075796426, -118.27394922752919),
  ('8090', 33.829672260302559, -118.25813646355425),
  ('2473', 33.828508462610635, -118.26042972591411),
  ('4829', 33.855842782830187, -118.26092459081056),
  ('2146', 33.854163091468706, -118.25182108131828),
  ('8103', 33.850221792937838, -118.25123219016820),
  ('2530', 33.854279212298579, -118.23910245110568),
  ('3384', 33.836828145453431, -118.24013335481943),
  ('3466', 33.836104377161050, -118.21395201265896),
  ('7329', 33.814121266728080, -118.28174747972790),
  ('2301', 33.776154708112159, -118.26544565238683),
  ('8868', 33.832953103457122, -118.21518578809419),
  ('6867', 33.787789843807076, -118.26229444318122)
) as coordinates(location_code, latitude, longitude)
where location.location_code = coordinates.location_code;

update public.location_information
set latitude = 33.740688530579675,
    longitude = -118.30920444605104
where school_name = 'Willenberg Special Ed' and location_code is null;

drop function if exists public.update_location_information(text, bigint, text, text, text, text, text, text, text, text, text, text);

alter table public.location_information
  drop column if exists supervisor_name,
  drop column if exists supervisor_email,
  drop column if exists supervisor_cell;

create or replace function public.update_location_information(
  p_supervisor_pin text,
  p_id bigint,
  p_location_code text,
  p_school_name text,
  p_manager_name text,
  p_site_type text,
  p_counting_claiming text,
  p_cafeteria_phone text,
  p_school_phone text,
  p_latitude double precision,
  p_longitude double precision
) returns public.location_information
language plpgsql
security definer
set search_path = public
as $$
declare
  v_record public.location_information;
begin
  if public.verify_supervisor_pin(p_supervisor_pin) is not true then
    raise exception 'Supervisor authorization failed';
  end if;
  if nullif(trim(p_school_name), '') is null then
    raise exception 'School name is required';
  end if;
  if p_latitude is not null and (p_latitude < -90 or p_latitude > 90) then
    raise exception 'Latitude must be between -90 and 90';
  end if;
  if p_longitude is not null and (p_longitude < -180 or p_longitude > 180) then
    raise exception 'Longitude must be between -180 and 180';
  end if;

  update public.location_information
  set location_code = nullif(trim(p_location_code), ''),
      school_name = trim(p_school_name),
      manager_name = nullif(trim(p_manager_name), ''),
      site_type = upper(nullif(trim(p_site_type), '')),
      counting_claiming = upper(nullif(trim(p_counting_claiming), '')),
      cafeteria_phone = nullif(trim(p_cafeteria_phone), ''),
      school_phone = nullif(trim(p_school_phone), ''),
      latitude = p_latitude,
      longitude = p_longitude,
      updated_at = now()
  where id = p_id
  returning * into v_record;

  if v_record.id is null then raise exception 'Location record not found'; end if;
  return v_record;
end;
$$;

revoke all on function public.update_location_information(text, bigint, text, text, text, text, text, text, text, double precision, double precision) from public;
grant execute on function public.update_location_information(text, bigint, text, text, text, text, text, text, text, double precision, double precision) to anon, authenticated;
