-- Shared manager/supervisor area location directory.
create table if not exists public.location_information (
  id bigint generated by default as identity primary key,
  location_code text unique,
  school_name text not null,
  manager_name text,
  site_type text,
  counting_claiming text,
  cafeteria_phone text,
  school_phone text,
  supervisor_name text,
  supervisor_email text,
  supervisor_cell text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create index if not exists location_information_school_name_idx
  on public.location_information (school_name);

alter table public.location_information enable row level security;

drop policy if exists "location information is readable" on public.location_information;
create policy "location information is readable"
  on public.location_information for select
  to anon, authenticated
  using (active = true);

revoke insert, update, delete on public.location_information from anon, authenticated;
grant select on public.location_information to anon, authenticated;

insert into public.location_information (
  location_code, school_name, manager_name, site_type, counting_claiming,
  cafeteria_phone, school_phone, supervisor_name, supervisor_email, supervisor_cell
) values
  ('8575', 'CARSON HS', 'SMTIH, KAWANE', 'Prep', 'CEP', '(310) 847-6048', '(310) 847-6000', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('8529', 'BANNING HS', 'JACKSON, NADINE', 'Prep', 'CEP', '(310) 847-3757', '(310) 847-3700', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('8487', 'WHITE MS', 'LOPEZ, TENNILLE', 'Prep', 'CEP', '(310) 328-1341', '(310) 783-4900', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('6867', 'BRIDGES SPAN', 'ESCOBAR, GABRIEL', 'Prep', 'CEP', '(310) 522-5415', '(310) 522-5400', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('8103', 'CURTISS MS', 'Bogdanovich, Carrie', 'Prep', 'CEP', '(310) 661-4573', '(310) 661-4500', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('8090', 'CARNEGIE MS', 'OCEGUERA, HERMINIA', 'Prep', 'CEP', '(310) 952-5730', '(310) 952-5700', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('7781', 'WILMINGTON PARK EL', 'WILSON, TONISHA', 'Prep', 'CEP', '(310) 834-5996', '(310) 518-7460', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2301', 'DE LA TORRE EL', 'RUIZ, MARIA', 'Prep', 'CEP', '(310) 847-1438', '(310) 847-1400', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('4014', 'FRIES EL', 'MARTINEZ DAMIAN, CECILIA', 'Prep', 'CEP', '(310) 834-6101', '(310) 834-6431', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2527', 'BROAD EL', 'WOODALL, TOCCARA', 'Prep', 'CEP', '(310) 835-5368', '(310) 835-3118', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2890', 'CATSKILL EL', 'DELA CRUZ-KEATING, LUZ', 'Prep', 'CEP', '(310) 835-4229', '(310) 834-7241', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2815', 'CAROLDALE LC', 'MIYASATO, BINH', 'Prep', 'CEP', '(310) 328-7489', '(310) 320-8570', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('7329', '232ND PL EL', 'HOLGUIN, GLORIA', 'Prep', 'CEP', '(310) 835-7343', '(310) 830-8710', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('7419', 'VAN DEENE EL', 'Peter', 'Prep', 'CEP', '(310) 320-1863', '(310) 320-8680', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('3452', 'DOLORES EL', 'SPRAGUE, TAMMY', 'NNC', 'CEP', '(310) 834-4983', '(310) 834-2565', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2089', 'AMBLER EL', 'WILSON, TRISTAN', 'NNC', 'CEP', '(310) 532-5815', '(310) 532-4090', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('4041', 'GARDENA EL', 'RUIZ, MARIA', 'Prep', 'CEP', '(310) 329-8326', '(310) 324-6967', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('5753', '186TH ST EL', 'MITCHELL, MARGARET', 'Prep', 'CEP', '(310) 323-2070', '(310) 324-1153', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2530', 'BROADACRES EL', 'PARKS, KHIRA', 'NNC', 'CEP', '(310) 537-1030', '(310) 537-1980', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2146', 'ANNALEE EL', 'Williams, Lachelle', 'NNC', 'CEP', '(310) 635-0470', '(310) 537-4740', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('4829', 'LEAPWOOD EL', 'SALVADOR, ROBERTO', 'NNC', 'CEP', '(310) 532-2106', '(310) 327-8245', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('7205', 'TOWNE EL', 'RAMIREZ, LOYDA', 'Prep', 'CEP', '(310) 323-3880', '(310) 329-3505', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2473', 'BONITA EL', 'DAWSON, BRITTNEY', 'NNC', 'CEP', '(310) 835-8197', '(310) 834-8588', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('3384', 'DEL AMO EL', 'SPEARS, TIANT', 'NNC', 'CEP', '(310) 830-4084', '(310) 830-5351', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('8868', 'RANCHO DOMINGUEZ PREP HS', 'WILSON, TONAE', 'Prep', 'CEP', '(310) 847-6427', '(310) 847-6400', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('3466', 'DOMINGUEZ EL', 'MENENDEZ, MELBYN', 'Prep', 'CEP', '(310) 834-6928', '(310) 835-7137', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'),
  ('2836', 'CARSON EL', 'AVILA, LILIANA', 'Prep', 'CEP', '(310) 834-4218', '(310) 834-4508', 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983')
on conflict (location_code) do update set
  school_name = excluded.school_name,
  manager_name = excluded.manager_name,
  site_type = excluded.site_type,
  counting_claiming = excluded.counting_claiming,
  cafeteria_phone = excluded.cafeteria_phone,
  school_phone = excluded.school_phone,
  supervisor_name = excluded.supervisor_name,
  supervisor_email = excluded.supervisor_email,
  supervisor_cell = excluded.supervisor_cell;

-- This source row has no location code, so it remains browseable but cannot be a manager login location yet.
insert into public.location_information (
  location_code, school_name, manager_name, site_type, counting_claiming,
  cafeteria_phone, school_phone, supervisor_name, supervisor_email, supervisor_cell
)
select null, 'Willenberg Special Ed', 'Garcia, Berenice', 'NNC', null,
  null, null, 'Huy Nguyen', 'huy.l.nguyen@lausd.net', '(213) 434-7983'
where not exists (
  select 1 from public.location_information where school_name = 'Willenberg Special Ed'
);

create or replace function public.update_location_information(
  p_supervisor_pin text,
  p_id bigint,
  p_location_code text,
  p_school_name text,
  p_manager_name text,
  p_site_type text,
  p_counting_claiming text,
  p_cafeteria_phone text,
  p_school_phone text,
  p_supervisor_name text,
  p_supervisor_email text,
  p_supervisor_cell text
) returns public.location_information
language plpgsql
security definer
set search_path = public
as $$
declare
  v_record public.location_information;
begin
  if public.verify_supervisor_pin(p_supervisor_pin) is not true then
    raise exception 'Supervisor authorization failed';
  end if;

  if nullif(trim(p_school_name), '') is null then
    raise exception 'School name is required';
  end if;

  update public.location_information
  set location_code = nullif(trim(p_location_code), ''),
      school_name = trim(p_school_name),
      manager_name = nullif(trim(p_manager_name), ''),
      site_type = nullif(trim(p_site_type), ''),
      counting_claiming = nullif(trim(p_counting_claiming), ''),
      cafeteria_phone = nullif(trim(p_cafeteria_phone), ''),
      school_phone = nullif(trim(p_school_phone), ''),
      supervisor_name = nullif(trim(p_supervisor_name), ''),
      supervisor_email = nullif(trim(p_supervisor_email), ''),
      supervisor_cell = nullif(trim(p_supervisor_cell), ''),
      updated_at = now()
  where id = p_id
  returning * into v_record;

  if v_record.id is null then
    raise exception 'Location record not found';
  end if;

  return v_record;
end;
$$;

revoke all on function public.update_location_information(text, bigint, text, text, text, text, text, text, text, text, text, text) from public;
grant execute on function public.update_location_information(text, bigint, text, text, text, text, text, text, text, text, text, text) to anon, authenticated;
